@startuml 翡翠骑士
title 翡翠骑士

skinparam{
    objectbackgroundColor White
    ' classbackgroundColor White
}
hide empty members

!$now_at_ch=0
!$now_at_node=0

!function $wrap($text, $width=15)
    !if %strlen($text) <= $width
!$out = $text
    !else
        !$out = ""
        !$pos = $width
        !$cut = ""
        !while %strlen($text) > $width
            !$cut = $pos
            !if $pos < 0
                !$out = $out + %substr($text, 0, $width)
                !$text = %substr($text, $width, %strlen($text) - $width +1)
            !else
                !$out = $out + %substr($text, 0, $cut)
                !$text = %substr($text, $cut, %strlen($text) - $cut)
            !endif
            !if %strlen($text) > 0
                !$out = $out + "\n"
            !endif
            !$pos = $width
            !$cut = ""
        !endwhile
        !if %strlen($text) > 0
            !$out = $out + $text
        !endif
    !endif
!return $out
!endfunction

!function $node($ch,$index)
!return $ch+"_"+$index
!endfunction

!function $node($ch,$index) return $ch+"_"+$index
!function $node_near($index) return $node($now_at_ch,$index)
!function $node_now() return $node($now_at_ch,$now_at_node)

!function $choice($a,$b,$c=0)
!if ($c==0)
!return $a+"_"+$b
!else
!return $a+"_"+$b+"_"+$c
!endif
!endfunction

!function $choice_near($b,$c) return $choice($node_near($b),$c)

!procedure $tag($node,$name)
    !if ($name == "end")
$node <<(E,Red)>>
class $node #LightBlue
    !elseif ($name == "bruce")
$node <<(B,Gold)>>
class $node #LightGray
    !elseif ($name=="sinestro")
$node <<(S,Magenta)>>
class $node #Gold
    !endif
!endprocedure

!procedure $link($src,$dst,$index="None",$des="None")
    !if ($index=="None")
$src --> $dst
    !elseif ($des=="None")
$src --> $dst:$index
    !else
$src --> $dst:$index\n$wrap($des,10)
    !endif
!endprocedure

!procedure $link_this($dst,$index="None",$des="None")
$link($node_now(),$dst,$index,$des)
!endprocedure

!procedure $link_self($dst,$index="None",$des="None")
!if ($index=="None")
$link($node_now(),$dst,$index,$des)
!else
$link($node_now(),$dst,$choice($node_now(),$index),$des)
!endif
!endprocedure

!procedure $new($node,$context,$type="None")
    !if ($type=="None")
object $node {
    !else
class $node {
    !endif
    $wrap($context)
}
$tag($node,$type)
!endprocedure

!procedure $new_there($context,$type="None")
$new($node_now(),$context,$type)
!endprocedure

!procedure $step($context,$type="None",$chapter=0)
!if ($chapter==0)
!$now_at_node=$now_at_node+1
!else
!$now_at_node=1
!$now_at_ch=$chapter
!endif
$new_there($context,$type)
!endprocedure

!procedure $init_node($choices)
!$t=1
!foreach $tmp in $choices.data
$link_self($node_near($tmp.dst),$t,$tmp.des)
!$t=$t+1
!endfor
!endprocedure

$step("游戏开始","None",1)
!$tmp={"data":[
        {"dst":2,"des":"继续前进"},
        {"dst":3,"des":"转头回去"},
        {"dst":4,"des":"原地睡一觉"}]}
$init_node($tmp)
$step("见到树上奇怪的影子，翡翠剑上的孔洞发烫，警惕着前方的风险")
!$tmp={"data":[
        {"dst":5,"des":"追上去"}]}
$init_node($tmp)
$link_this($node_near(3),$choice_near(1,2),"转头回去")
$step("渐渐找回了路，在夜晚的大树上见到了脚印")
!$tmp={"data":[
        {"dst":6,"des":"原地蹲守"},
        {"dst":7,"des":"不关我事"},
        {"dst":8,"des":"爬上去"}]}
$init_node($tmp)
$step("醒来身边有一团篝火，还有一个人，嘲讽你在野外睡觉都不点火","sinestro")
!$tmp={"data":[
        {"dst":9,"des":"呛回去"},
        {"dst":10,"des":"谢谢你"},
        {"dst":11,"des":"你哪位"}]}
$init_node($tmp)
$step("你追着古怪的阴影一路前进，一直到一处深邃的阴影，一片叶子恰好落在翡翠剑的孔洞上，瞬间燃起了火")
!$tmp={"data":[
        {"dst":12,"des":"直接进去"},
        {"dst":13,"des":"四处看看（知识+）"}]}
$init_node($tmp)
$step("你在隐蔽处等到天亮，终于听见声响，一个身影从岩缝里钻出来，青苔在他挥手间盖住了脚印，你也在这个时候看清了他的脸，是奥利。你回了小镇。")
!$tmp={"data":[
        {"dst":52,"des":"去找奥利"},
        {"dst":18,"des":"去找卡萝"}]}
$init_node($tmp)
$step("你回了小镇，深夜街上空无一人，但有座房子依然亮着灯，是巴里家")
!$tmp={"data":[
        {"dst":14,"des":"去敲门（知识+2)"},
        {"dst":17,"des":"回家睡觉"}]}
$init_node($tmp)
$step("摔晕了，醒来已经回到了小镇，巴里说是奥利把你送回来的")
!$tmp={"data":[
        {"dst":16,"des":"找人带路去龙骨雪山"}]}
$init_node($tmp)
$link_this($node_near(52),$choice_near(6,1),"去见他")
$step("驯化度-")
$link_this($node_near(11),$choice_near(4,3),"你哪位")
$step("好感度+","sinestro")
$link_this($node_near(11),$choice_near(4,3),"你哪位")
$step("他自称瑟尔。他问你是干嘛的，你告诉他你是讨伐魔王的勇者，他问你为什么要讨伐魔王")
!$tmp={"data":[
        {"dst":55,"des":"为了出名"},
        {"dst":56,"des":"他是全大陆的威胁"},
        {"dst":57,"des":"我想做点什么"}]}
$init_node($tmp)
$step("从黑洞里进去，是一个隧道，石壁上长的晶石发着冷白的光，你一路前进，晶石颜色愈发五花八门起来，有一些已经落到了地上，你准备捡一块")
!$tmp={"data":[
        {"dst":20,"des":"捡块红的"},
        {"dst":21,"des":"捡块蓝的"},
        {"dst":22,"des":"捡块紫的"},
        {"dst":23,"des":"捡块绿的"}]}
$init_node($tmp)
$step("你绕着黑洞走了走，在一棵树上发现了一个刀刻般的痕迹，痕迹很新，好像才刻下没多久。","bruce")
$link_this($node_near(12))
$step("巴里用鹅毛笔在羊皮纸上画着些什么，见到你很惊讶，问你怎么回来了")
!$tmp={"data":[
        {"dst":47,"des":"路上迷路了"},
        {"dst":48,"des":"想你了啊（好感度+）"},
        {"dst":49,"des":"后悔了"}]}
$init_node($tmp)
$step("我再给你一次机会")
$link_this($node_near(19),$choice_near(17,2))
$step("附近有几个小镇，去哪里问路")
1_16-->2_1:1_16_1\n河流上游的银鳞村
1_16-->2_2:1_16_2\n沿大路走，树林里的百羽镇

$step("你还要继续冒险吗")
1_17-->end_1:1_17_1\n不了，再见
$new("end_1","END 01 无事发生","end")
1_17-->1_19:1_17_2\n不了，再见
$step("你问卡萝还记不记得那棵大树，有没有看到过什么奇怪的东西，卡萝是炼金术师，她说，捡到了一支箭")
object 1_18{
    知识+3
}
1_18-->1_52:1_6_1\n去找奥利
$step("那你接下来要做什么")
1_19-->1_16:1_8_2
1_19-->1_15:1_8_2
$step("火属性晶石")
1_20-->1_24:1_12_0\n继续前进
$step("水属性晶石")
1_21-->1_24:1_12_0\n继续前进
$step("空间属性晶石")
1_22-->1_24:1_12_0\n继续前进
$step("生命属性晶石","bruce")
1_23-->1_24:1_12_0\n继续前进
$step("继续前进，周围的晶石越来越多，你眼前一亮，走进了一间屋子，似乎是一间魔法师的书房。书房另一端，有一扇门")
1_24-->1_25:1_24_1\n书架
1_24-->1_26:1_24_2\n挂毯
1_24-->1_27:1_24_2\n卷轴
1_24-->1_28:1_24_2\n墙上
1_24-->1_29:1_24_5\n直接出门\n智力-2
$step("光明符文","bruce")
1_25-->1_29:1_24_0
$step("黑暗符文")
1_26-->1_29:1_24_0
$step("大地符文")
1_27-->1_29:1_24_0
$step("雷霆符文")
1_28-->1_29:1_24_0
$step("你走出去，一步踏出，却看不到路。周围是一片无边无际的星空，转身，门却已经不见了。你只能往前走。隐约似乎看到了一个黑影")
1_29-->1_30:1_29_1\n追上去
1_29-->1_34:1_29_2\n光明符文
$step("追了两步就找不到了")
1_30-->1_39:1_39
$step("你四处乱走，突然听到一声脆响，星空碎裂，你发现自己站在湖边。一个黑影划过你的眼角，转瞬消失在了森林里。")
1_31-->1_32:1_31_1\n追
1_31-->1_33:1_31_2\n不追
$step("追不上，你又累又饿，回了湖边")
1_32-->1_33:1_31_2
$step("你在湖边略作休整，沿着水路出去，发现自己到了银鳞村。")
1_33-->2_1:1_16_1
$step("是一个披着漆黑斗篷的人，他朝你走过来","bruce")
1_34-->1_35:1_34_1\n这是哪里
1_34-->1_36:1_34_2\n你是谁
$step("黑暗法师塔遗迹")
1_35-->1_37:1_34_0\n这是什么地方
1_35-->1_36
$step("和你一样的人")
1_36-->1_37:1_34_0\n这是什么地方
1_36-->1_35
$step("这里是一个法阵，已经被黑暗力量浸染，要出去，需要毁掉阵眼。")
1_37-->1_38:1_37_1\n你能做到？
1_37-->1_39:1_37_2\n我能怎么帮你？\n（好感+1）
$step("他再没搭理过你（好感-5）")
1_38-->1_31:1_38_1
$step("找不对劲的地方")
1_39-->1_40:1_39_1\n（知识>=1）\n脚下踢到了一个黑漆漆的球形
$step("你观察了这个球")
1_40-->1_41:1_40_1\n有生命晶石
1_40-->1_45:1_40_2\n有生命晶石
1_40-->1_31:1_40_3\n没有生命晶石也没见到布鲁斯
$step("你刚想叫他过来，口袋里的晶石却发出了耀眼的绿光，自行飞出，落进了原本大小不合适的翡翠剑的孔洞。你挥动翡翠剑，打碎了晶石。星空随之碎裂。（好感+10）（没见过的话，好感+4）")
1_41-->1_44:1_41_3\n（好感+4）\n没见到布鲁斯
1_41-->1_46:1_41_4\n（好感+10）
$step("他给你介绍了法师塔废墟与黑暗力量的关系。（知识+5）","bruce")
1_42-->1_43:1_41_24\n问他的名字
$step("他叫布鲁斯，是哥谭人，但你不知道哥谭在哪儿，场面一度十分尴尬。他说，要想多知道翡翠剑的事，可以去天使城。你告别了他，踏上去天使城的路。","bruce")
1_43-->2_3:1_16_3\n海边的天使城
$step("你发现自己身处湖边，一个黑影划过眼角")
1_44-->1_31
$step("你叫他过来，他让你走远些，用飞镖打碎的晶石，星空随之碎裂。他向你告别，你才想起还不知道他的名字，你大喊自己的名字，不知道他听没听见。（好感+2）")
1_45-->1_33:1_31_2\n不追
$step("见到布鲁斯","bruce")
1_46-->1_42:1_41_1\n先问问他法师塔的事
1_46-->1_43:1_41_24\n问他的名字
$step("长老团给的地图不准，你找不到方向，担心越错越远，就回来了，巴里提议去银鳞村找人问路")
1_47-->2_1:1_16_1
$step("他笑着说你别闹了，说正经的呢")
1_48-->1_47:1_14_1
$step("巴里有些担心，问你为什么")
1_49-->end_1:1_49_1\n怕自己不够强
1_49-->1_50:1_49_2\n（孔洞发烫）\n知道的太少，准备去找长老团
1_49-->1_51:1_49_3\n（孔洞发烫）\n知道的太少，有个猜想\n要去百羽镇查证（知识+1）
$step("去找长老团询问翡翠剑的秘密，长老团让你去天使城（知识+3）")
1_50-->2_3:1_49_1
$step("去百羽镇")
1_51-->2_2:1_16_2
$step("奥利不在家，他家里有做了一半的箭支")
1_52-->1_53:1_52_1\n（看到卡萝的箭）
1_52-->1_54:1_52_2\n在屋里等他回来
$step("仔细看，虽然和那支材料不同，但一些细节上的处理却非常相似（知识+1）")
1_53-->1_54:1_52_2\n在屋里等他回来
$step("四处看看，发现一些端倪，等奥利回来，聊了聊，他带你去百羽镇")
1_54-->2_2:1_16_2
$step("（好感度-）我希望自己死后几十几百年，依然有人记得我的名字")
1_55-->1_58:1_11_4
$step("生在其中，无处可躲，为什么不直面未来？")
1_56-->1_58:1_11_4
$step("（驯化度+）一辈子只有这么长，不如拿来做点别人做不了的事","sinestro")
1_57-->1_58:1_11_4
$step("柴火突然炸了，把瑟尔吓了一跳")
1_58-->1_59:1_58_1\n（驯化度>=0）\n你就这么在野外点火的？
1_58-->1_60:1_58_2\n这点胆子，还敢在树林里过夜？
1_58-->1_61:1_58_3\n（好感度>=0）\n有点可爱
$step("（驯化度++）他没呛声","sinestro")
1_59-->1_62:1_58_4
$step("（驯化度-）与你何干")
1_60-->1_62:1_58_4
$step("（好感度-）他问你是不是疯了")
1_61-->1_62:1_58_4
$step("你把柴火重新收拾了一下，到了后半夜，突然感到不大对劲，瑟尔眼睛泛着金光，和你打了一架，好不容易把他制服")
1_62-->1_63:1_62_1\n（好感度>0或驯化度>0）
1_62-->1_64:1_62_2\n（都<0）把他制住
$step("瑟尔醒来，问你要不要上他")
1_63-->1_72:1_63_1\n答应
1_63-->end_3:1_63_2\n拒绝
$new("end_3","END 03 宁死不屈","end")
$step("失败，他一下子挣脱了你的控制，不知是不是你的错觉，那一瞬间他的身体似乎变成了烟雾。天亮后你继续前进，发现自己到了百羽镇附近，反倒还沿着你原定规划的路线前进")
1_64-->1_65:1_64_1\n进去补给一下
1_64-->1_66:1_64_2\n继续前进
$step("你听说百羽镇昨晚有人失踪了")
1_65-->1_66:1_64_2\n继续前进
$step("你又遇到了瑟尔")
1_66-->1_67:1_66_1\n（去了百羽镇）
1_66-->1_68:1_66_2\n邀请他一起上路
$step("你问失踪的人，和你有关吗？他痛快承认")
1_67-->1_69:1_67_1\n人在哪儿
1_67-->1_70:1_67_2\n你为什么要抓人
$step("你们一起走了一段，路边窜出一只兔子撞到他腿上，被黑暗力量缠绕，活活窒息而死")
1_68-->1_71:1_67_3
$step("回家了，也死了")
1_69-->1_71:1_67_3
$step("饿了")
1_70-->1_71:1_67_3
$step("你到底什么来头，他说，你也猜到了吧，我是你要杀的魔王啊")
1_71-->end_2:和他战斗
$new("end_2","END 02 出师未捷","end")
$step("第一步")
1_72-->1_73:1_72_1\n先亲
1_72-->1_73:1_72_2\n先摸（评分+2）
$step("第二步")
1_73-->1_74:1_73_1\n按地上（评分+3）
1_73-->1_74:1_73_2\n按墙上
$step("第三步")
1_74-->1_75:1_74_1\n里面（评分+5）
1_74-->1_75:1_74_2\n外面
$step("做完了")
1_75-->1_76:1_75_1\n（10分）好评（好感++）
1_75-->1_77:1_75_2\n（5_9分）中评
1_75-->end_4:1_75_3\n（0_4分）差评
$new("end_4","END 04 牡丹花下","end")
$step("他说下次再见，你肩上的牙印突然有点烫")
1_76-->1_78:1_76_1\n还有下次？
1_76-->1_79:1_76_2\n下次是什么时候
1_76-->1_80:1_76_3\n我怎么联系你
$step("做完他就把你踹一边了，天亮后你到了百羽镇")
1_77-->2_2:1_76_3\n我怎么联系你
$step("（驯服-）对")
1_78-->1_81:1_76_4
$step("到时候你就知道了")
1_79-->1_81:1_76_4
$step("（驯服+，好感+）你不能","sinestro")
1_80-->1_81:1_76_4
$step("你顺口问了一句，瑟尔给你指了翻越龙骨雪山的路，你决定跟着走")
1_81-->3_1:1_81_1
$step("银鳞村，图书馆","None",2)
2_1-->2_4:2_1_1\n魔法知识
2_1-->2_5:2_1_2\n传说记载
2_1-->2_6:2_1_3\n大陆历史
$step("百羽镇")
2_2-->2_8:2_2_1\n和奥利在一起\n进树林
2_2-->2_9:2_2_2\n（自己）\n进百羽镇
$step("天使城，神殿")
2_3-->2_24:2_3_1\n（翡翠剑异变3次）
2_3-->2_25:2_3_2\n（翡翠剑异变1次）
$step("黑暗吞食生命，光明消灭黑暗（知识+）")
2_4-->2_1
2_4-->2_7:2_1_4\n研究昨天为什么迷路
$step("精灵是大自然的孩子，也是生命的挚友（知识+）")
2_5-->2_1
2_5-->2_7:2_1_4\n研究昨天为什么迷路
$step("一千年前，黑暗力量也曾来袭过（知识+）")
2_6-->2_1
2_6-->2_7:2_1_4\n研究昨天为什么迷路
$step("翻出一份推论，涉及空间的禁咒级魔法会可能扭曲附近的空间（知识+）")
2_7-->3_2:2_7_1
$step("植物在奥利的指挥下移动，分出一条路来，沿着那条路走进去，你看到了一棵参天大树，简直有龙骨雪山那么高。奥利说真的有那么高，问你想先去哪里")
2_8-->2_10:2_8_1\n黑暗力量
2_8-->2_11:2_8_2\n四处逛逛
2_8-->2_12:2_8_3\n在奥利家见过箭\n箭
$step("遇到托马，他告诉你地图没有错，但你为什么会迷路，他也猜不出来")
2_9-->2_20:2_9_1\n（没看树）\n那我走了，去翻龙骨雪山
2_9-->2_21:2_9_2\n（没看树）\n你还知道别的怪事吗
2_9-->2_19:2_9_3\n（看树）\n你知道精灵吗
$step("奥利带你去问生命之树，生命之树是大陆上第一棵树，已经活了很多很多年，你刚站到它面前，生命之树上忽然伸出一根树枝，拍了拍翡翠剑")
2_10-->2_13:2_10_1\n躲开
2_10-->2_14:2_10_2\n不动
$step("精灵族的栖息地是被称作“生命之树”的植物，高耸入云，精灵是树上结的果子，落地化为人形，有操控自然之力的能力")
2_11-->2_17:2_11_1\n自然之力？
2_11-->2_18:2_11_2\n所以你不是人？
$step("（奥利好感+3）那个徽记是他的精灵名，意为橄榄，敢说出去你就死定了")
2_12-->2_8
$step("根本没用")
2_13-->2_14:2_10_2
$step("（声望+2）生命之树把翡翠剑抽出来，说好久没见过它了")
2_14-->2_15:2_14_1\n上次见是什么时候
2_14-->2_33:2_14_2\n翡翠剑有异动\n这把剑是不是有什么不同凡响的地方\n智力+2
$step("上次见它，还是在阿宾的手里，你问阿宾是谁，生命之树告诉你是很多年前讨伐魔王的勇士，他是精灵族的朋友，从这里出发去翻越龙骨雪山，但再也没有回来")
2_15-->2_16:2_15_1\n道谢离开
$step("你在精灵族休息了一夜，或许是生命的滋养，你感到自己充满精力")
2_16-->3_3:2_16_1\n沿阿宾的路前进
$step("魔法师所谓的自然元素之一的生命，这种能力来自于生命之树，但因为黑暗力量的侵袭，他们已经若小了很多（知识+1）")
2_17-->2_10:2_11_3\n黑暗力量
$step("奥利说我是半人，因为黑暗力量，生命之树几十年没结过果子了")
2_18-->2_10:2_11_3\n黑暗力量
$step("绝迹很久了")
2_19-->2_9:没看树
$step("他问你问这个干什么，你说要去讨伐魔王，他劝你最好别去")
2_20-->2_22:2_20_1\n你还知道什么？
2_20-->2_23:2_20_2\n不想说，我就不问了
$step("今天上午有几个昨天去打猎的人回来，也说昨天莫名其妙地迷路了")
2_21-->2_20:2_9_1\n那我走了，去翻龙骨雪山
$step("托马就是当年捡到翡翠剑的猎人，当时半空中有个黑茧，他用藤蔓够了一下，死了一大片植物，黑茧里绿光大盛，他再睁眼，剑就跌到了地上。（知识+3）")
2_22-->2_23:2_20_2\n不想说，我就不问了
$step("你和托马分开，沿着原定路线向龙骨雪山前进")
2_23-->3_2:2_7_1
$step("翡翠剑在你步入神殿的时候突然飞了起来，一剑刺进了神殿中央的石台，神殿祭司甘瑟走出来，问是怎么回事")
2_24-->2_26:2_24_1\n我也不知道
2_24-->2_27:2_24_2\n（知识>5）\n这下面是不是有黑暗力量
$step("你告诉守卫，是欧阿的长老团让你来这里问问翡翠剑的事，过了一会儿，祭司甘瑟走了出来")
2_25-->2_28:2_25_1\n我来是想了解一下翡翠剑
$step("甘瑟看见翡翠剑，似乎明白了什么，但他没有告诉你")
2_26-->2_28:2_25_1\n我来是想了解一下翡翠剑
$step("是的，石台下镇压的是天使出现的原因，一直封闭着，没有人打开过（智力+2）")
2_27-->2_28:2_25_1\n我来是想了解一下翡翠剑
$step("翡翠剑是在天使城铸造的。工匠是矮人族，也有精灵、魔法导师和炼金师的参与，它有一个特别的功能，就是感应黑暗力量。剑柄上原本镶嵌着一个被称作剑心的宝石，可以把生命力量转换为光明。甘瑟不知道剑心是怎么制造的，也不知道它为什么会消失")
2_28-->2_29:2_28_1\n那你知道什么
2_28-->2_30:2_28_2\n那谁会知道\n（智力+）
$step("我知道谁知道")
2_29-->2_30:2_28_2\n那谁会知道
$step("毁掉剑心的人一定知道，除此之外，就是上一任的翡翠剑主人，阿宾")
2_30-->2_31:2_30_1\n他还活着？
2_30-->2_32:2_30_2\n这不是废话吗\n（智力-）
$step("他死在了龙骨山脉里，甘瑟做过很多探查，大概划出了一个范围")
2_31-->3_4:2_31_1
$step("甘瑟生气了，你还听不听")
2_32-->2_31:2_30_1\n他还活着？
$step("是的，它是专为与魔王作战锻造的")
2_33-->2_15:2_14_1\n上次见是什么时候
$step("瑟尔指的路下面是一片峭壁，隐约能看见一些可以搭手的藤蔓","None",3)
!$tmp={"data":[
        {"dst":5,"des":"爬（驯服度+）"},
        {"dst":30,"des":"不爬"}]}
$init_node($tmp)
@enduml