@startuml 翡翠骑士
' left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title 翡翠骑士

object 1_1{
    游戏开始
}
1_1-->1_2:1-1-1\n继续前进
1_1-->1_3:1-1-2\n转头回去
1_1-->1_4:1-1-3\n原地睡一觉
1_2-->1_5:1-2-1\n追上去
object 1_2{
    见到树上奇怪的影子，翡翠剑上的
    孔洞发烫，警惕着前方的风险
}
1_2-->1_3:1-1-2
object 1_3{
    渐渐找回了路，在夜晚的大树上见
    到了脚印
}
1_3-->1_6:1-3-1\n原地蹲守
1_3-->1_7:1-3-2\n不关我事
1_3-->1_8:1-3-3\n爬上去
object 1_4{
    醒来身边有一团篝火，还有一个人，
    嘲讽你在野外睡觉都不点火
}
1_4-->1_9:1-4-1\n呛回去
1_4-->1_10:1-4-2\n谢谢你
1_4-->1_11:1-4-3\n你哪位
object 1_5{
    你追着古怪的阴影一路前进，一直
    到一处深邃的阴影，一片叶子恰好
    落在翡翠剑的孔洞上，瞬间燃起了
    火
}
1_5-->1_12:1-5-1\n直接进去
1_5-->1_13:1-5-2\n四处看看
object 1_6{
    你在隐蔽处等到天亮，终于听见声
    响，一个身影从岩缝里钻出来，青
    苔在他挥手间盖住了脚印，你也在
    这个时候看清了他的脸，是奥利。
    你回了小镇。
}
1_6-->1_52:1-6-1\n去找奥利
1_6-->1_18:1-6-2\n去找卡萝
object 1_7{
    你回了小镇，深夜街上空无一人，
    但有座房子依然亮着灯，是巴里家
}
1_7-->1_14:1-7-1\n去敲门
1_7-->1_17:1-7-2\n回家睡觉
object 1_8{
    摔晕了，醒来已经回到了小镇，巴
    里说是奥利把你送回来的
}
1_8-->1_52:1-6-1\n去见他
1_8-->1_16:1-8-2\n找人带路去龙骨雪山
object 1_9{
    呛回去
    驯化度-
}
1_9-->1_11:1-4-3
object 1_10{
    谢谢你
    好感度+
}
1_10-->1_11:1-4-3
object 1_11{
    他自称瑟尔。他问你是干嘛的，你
    告诉他你是讨伐魔王的勇者，他问
    你为什么要讨伐魔王
}
1_11-->1_55:1-11-1\n为了出名
1_11-->1_56:1-11-2\n他是全大陆的威胁
1_11-->1_57:1-11-3\n我想做点什么
object 1_12{
    从黑洞里进去，是一个隧道，石壁
    上长的晶石发着冷白的光，你一路
    前进，晶石颜色愈发五花八门起来
    ，有一些已经落到了地上，你准备
    捡一块
}
1_12-->1_20:1-12-1\n捡块红的
1_12-->1_21:1-12-2\n捡块蓝的
1_12-->1_22:1-12-3\n捡块紫的
1_12-->1_23:1-12-4\n捡块绿的
object 1_13{
    知识+
    你绕着黑洞走了走，在一棵树上发
    现了一个刀刻般的痕迹，痕迹很新
    ，好像才刻下没多久。
}
1_13-->1_12:1-5-1
object 1_14{
    知识+2
    巴里用鹅毛笔在羊皮纸上画着些什
    么，见到你很惊讶，问你怎么回来
    了
}
1_14-->1_47:1-14-1\n路上迷路了
1_14-->1_48:1-14-2\n想你了啊
1_14-->1_49:1-14-3\n路上迷路了
object 1_15{
    我再给你一次机会
}
1_15-->1_19:1-17-2
object 1_16{
    附近有几个小镇，去哪里问路
}
1_16-->2_1:1-16-1\n河流上游的银鳞村
1_16-->2_2:1-16-2\n沿大路走，树林里的百羽镇
object 1_17{
    你还要继续冒险吗
}
1_17-->end_1:1-17-1\n不了，再见
object end_1{
    END 01 无事发生
}
1_17-->1_19:1-17-2\n不了，再见
object 1_18{
    知识+3
    你问卡萝还记不记得那棵大树，有
    没有看到过什么奇怪的东西，卡萝
    是炼金术师，她说，捡到了一支箭
}
1_18-->1_52:1-6-1\n去找奥利
object 1_19{
    那你接下来要做什么
}
1_19-->1_16:1-8-2
1_19-->1_15:1-8-2
object 1_20{
    火属性晶石
}
1_20-->1_24:1-12-0\n继续前进
object 1_21{
    水属性晶石
}
1_21-->1_24:1-12-0\n继续前进
object 1_22{
    空间属性晶石
}
1_22-->1_24:1-12-0\n继续前进
object 1_23{
    生命属性晶石
}
1_23-->1_24:1-12-0\n继续前进
object 1_24{
    继续前进，周围的晶石越来越多，
    你眼前一亮，走进了一间屋子，似
    乎是一间魔法师的书房。书房另一
    端，有一扇门
}
1_24-->1_25:1-24-1\n书架
1_24-->1_26:1-24-2\n挂毯
1_24-->1_27:1-24-2\n卷轴
1_24-->1_28:1-24-2\n墙上
1_24-->1_29:1-24-5\n直接出门\n智力-2
object 1_25{
    光明符文
}
1_25-->1_29:1-24-0
object 1_26{
    黑暗符文
}
1_26-->1_29:1-24-0
object 1_27{
    大地符文
}
1_27-->1_29:1-24-0
object 1_28{
    雷霆符文
}
1_28-->1_29:1-24-0
object 1_29{
    你走出去，一步踏出，却看不到路
    。周围是一片无边无际的星空，转
    身，门却已经不见了。你只能往前
    走。隐约似乎看到了一个黑影
}
1_29-->1_30:1-29-1\n追上去
1_29-->1_34:1-29-2\n光明符文
object 1_30{
    追了两步就找不到了
}
1_30-->1_39:1_39
object 1_31{
    你四处乱走，突然听到一声脆响，
    星空碎裂，你发现自己站在湖边。
    一个黑影划过你的眼角，转瞬消失
    在了森林里。
}
1_31-->1_32:1-31-1\n追
1_31-->1_33:1-31-2\n不追
object  1_32{
    追不上，你又累又饿，回了湖边
}
1_32-->1_33:1-31-2
object  1_33{
    你在湖边略作休整，沿着水路出去
    ，发现自己到了银鳞村。
}
1_33-->2_1:1-16-1
object 1_34{
    是一个披着漆黑斗篷的人，他朝你
    走过来
}
1_34-->1_35:1-34-1\n这是哪里
1_34-->1_36:1-34-2\n你是谁
object 1_35{
    黑暗法师塔遗迹
}
1_35-->1_37:1-34-0\n这是什么地方
object 1_36{
    和你一样的人
}
1_36-->1_37:1-34-0\n这是什么地方
object 1_37{
    这里是一个法阵，已经被黑暗力量
    浸染，要出去，需要毁掉阵眼。
}
1_37-->1_38:1-37-1\n你能做到？
object 1_38{
    好感-5
    他再没搭理过你
}
1_38-->1_31:1-38-1
object 1_39{
    找不对劲的地方
}
1_39-->1_40:1-39-1\n（知识>=1）\n脚下踢到了一个黑漆漆的球形
object 1_40{
    你观察了这个球
}
1_40-->1_41:1-40-1\n有生命晶石
1_40-->1_45:1-40-2\n有生命晶石
1_40-->1_31:1-40-3\n没有生命晶石也没见到布鲁斯
object 1_41{
    你刚想叫他过来，口袋里的晶石却
    发出了耀眼的绿光，自行飞出，落
    进了原本大小不合适的翡翠剑的孔
    洞。你挥动翡翠剑，打碎了晶石。
    星空随之碎裂。（好感+10）（没
    见过的话，好感+4）
}
1_41-->1_44:1-41-3\n（好感+4）\n没见到布鲁斯
1_41-->1_46:1-41-4\n（好感+10）
object 1_42{
    他给你介绍了法师塔废墟与黑暗力
    量的关系。
    知识+5
}
1_42-->1_43:1-41-24\n问他的名字
object 1_43{
    他叫布鲁斯，是哥谭人，但你不知
    道哥谭在哪儿，场面一度十分尴尬
    。他说，要想多知道翡翠剑的事，
    可以去天使城。你告别了他，踏上
    去天使城的路。
}
1_43-->2_3:1-16-3\n海边的天使城
object 1_44{
    你发现自己身处湖边，一个黑影划
    过眼角
}
1_44-->1_31
object 1_45{
    好感+2
    你叫他过来，他让你走远些，用飞
    镖打碎的晶石，星空随之碎裂。他
    向你告别，你才想起还不知道他的
    名字，你大喊自己的名字，不知道
    他听没听见。
}
1_45-->1_33:1-31-2\n不追
object 1_46{
    见到布鲁斯
}
1_46-->1_42:1-41-1\n先问问他法师塔的事
1_46-->1_43:1-41-24\n问他的名字
object 1_47{
    长老团给的地图不准，你找不到方
    向，担心越错越远，就回来了，巴
    里提议去银鳞村找人问路
}
1_47-->2_1:1-16-1
object 1_48{
    好感度+
    他笑着说你别闹了，说正经的呢
}
1_48-->1_47:1-14-1
object 1_49{
    巴里有些担心，问你为什么
}
1_49-->end_1:1-49-1\n怕自己不够强
1_49-->1_50:1-49-2\n（孔洞发烫）\n知道的太少，准备去找长老团
1_49-->1_51:1-49-3\n（孔洞发烫）\n知道的太少，有个猜想\n要去百羽镇查证（知识+1）
object 1_50{
    去找长老团询问翡翠剑的秘密，长
    老团让你去天使城
    知识+3
}
1_50-->2_3:1-49-1
object 1_51{
    去百羽镇
}
1_51-->2_2:1-16-2
object 1_52{
    奥利不在家，他家里有做了一半的
    箭支
}
1_52-->1_53:1-52-1\n（看到卡萝的箭）
1_52-->1_54:1-52-2\n在屋里等他回来
object 1_53{
    仔细看，虽然和那支材料不同，但
    一些细节上的处理却非常相似
    知识+1
}
1_53-->1_54:1-52-2\n在屋里等他回来
object 1_54{
    四处看看，发现一些端倪，等奥利
    回来，聊了聊，他带你去百羽镇
}
1_54-->2_2:1-16-2
object 1_55{
    好感度-
    我希望自己死后几十几百年，依然
    有人记得我的名字
}
1_55-->1_58:1-11-4
object 1_56{
    生在其中，无处可躲，为什么不直
    面未来？
}
1_56-->1_58:1-11-4
object 1_57{
    驯化度+
    一辈子只有这么长，不如拿来做点
    别人做不了的事
}
1_57-->1_58:1-11-4
object 1_58{
    柴火突然炸了，把瑟尔吓了一跳
}
1_58-->1_59:1-58-1\n（驯化度>=0）\n你就这么在野外点火的？
1_58-->1_60:1-58-2\n这点胆子，还敢在树林里过夜？
1_58-->1_61:1-58-3\n（好感度>=0）\n有点可爱
object 1_59{
    驯化度++
    他没呛声
}
1_59-->1_62:1-58-4
object 1_60{
    驯化度-
    与你何干
}
1_60-->1_62:1-58-4
object 1_61{
    好感度-
    他问你是不是疯了
}
1_61-->1_62:1-58-4
object 1_62{
    你把柴火重新收拾了一下，到了后
    半夜，突然感到不大对劲，瑟尔眼
    睛泛着金光，和你打了一架，好不
    容易把他制服
}
1_62-->1_63:1-62-1\n（好感度>0或驯化度>0）
1_62-->1_64:1-62-2\n（都<0）把他制住
object 1_63{
    瑟尔醒来，问你要不要上他
}
1_63-->1_72:1-63-1\n答应
1_63-->end_3:1-63-2\n拒绝
object end_3{
    END 03 宁死不屈
}
object 1_64{
    失败，他一下子挣脱了你的控制，
    不知是不是你的错觉，那一瞬间他
    的身体似乎变成了烟雾。天亮后你
    继续前进，发现自己到了百羽镇附
    近，反倒还沿着你原定规划的路线
    前进
}
1_64-->1_65:1-64-1\n进去补给一下
1_64-->1_66:1-64-2\n继续前进
object 1_65{
    你听说百羽镇昨晚有人失踪了
}
1_65-->1_66:1-64-2\n继续前进
object 1_66{
    你又遇到了瑟尔
}
1_66-->1_67:1-66-1\n（去了百羽镇）
1_66-->1_68:1-66-2\n邀请他一起上路
object 1_67{
    你问失踪的人，和你有关吗？他痛
    快承认
}
1_67-->1_69:1-67-1\n人在哪儿
1_67-->1_70:1-67-2\n你为什么要抓人
object 1_68{
    你们一起走了一段，路边窜出一只
    兔子撞到他腿上，被黑暗力量缠绕
    ，活活窒息而死
}
1_68-->1_71:1-67-3
object 1_69{
    回家了，也死了
}
1_69-->1_71:1-67-3
object 1_70{
    饿了
}
1_70-->1_71:1-67-3
object 1_71{
    你到底什么来头，他说，你也猜到
    了吧，我是你要杀的魔王啊
}
1_71-->end_2:和他战斗
object end_2{
    END 02 出师未捷
}
object 1_72{
    先聊两句
}
1_72-->1_73:1-72-1\n先亲
1_72-->1_73:1-72-2\n先摸（评分+2）
object 1_73{
    第二步
}
1_73-->1_74:1-73-1\n按地上（评分+3）
1_73-->1_74:1-73-2\n按墙上
object 1_74{
    第三步
}
1_74-->1_75:1-74-1\n里面（评分+5）
1_74-->1_75:1-74-2\n外面
object 1_75{
    做完了
}
1_75-->1_76:1-75-1\n（10分）好评（好感++）
1_75-->1_77:1-75-2\n（5-9分）中评
1_75-->end_4:1-75-3\n（0-4分）差评
object end_4{
    END 04 牡丹花下
}
object 1_76{
    他说下次再见，你肩上的牙印突然
    有点烫
}
1_76-->1_78:1-76-1\n还有下次？
1_76-->1_79:1-76-2\n下次是什么时候
1_76-->1_80:1-76-3\n我怎么联系你
object 1_77{
    做完他就把你踹一边了，天亮后你到了百羽镇
}
1_77-->2_2:1-76-3\n我怎么联系你
object 1_78{
    驯服-
    对
}
1_78-->1_81:1-76-4
object 1_79{
    到时候你就知道了
}
1_79-->1_81:1-76-4
object 1_80{
    驯服+，好感+
    你不能
}
1_80-->1_81:1-76-4
object 1_81{
    你顺口问了一句，瑟尔给你指了翻
    越龙骨雪山的路，你决定跟着走
}
1_81-->3_1:1-81-1
@enduml