BRUCE_STORY_LINE = "bsl"
OLIVER_STORY_LINE = "osl"
SINESTRO_STORY_LINE = "ssl"
SINESTRO_LOVE = "sinl"
SINESTRO_TAME = "sint"

default_para = {
    OLIVER_STORY_LINE: 0,
    BRUCE_STORY_LINE: 1,
    SINESTRO_STORY_LINE: 1,
    SINESTRO_LOVE: 0,
    SINESTRO_TAME: 0
}
