name: Android APK

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: 25

            - name: Set up Python
              uses: actions/setup-python@v5

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            - name: Decode Keystore
              run: |
                  echo "${{ secrets.KEY_STORE_BASE64 }}" | base64 --decode > my-release-key.jks
                  echo "KEYSTORE_PATH=$(pwd)/my-release-key.jks" >> $GITHUB_ENV
                  echo "KEYSTORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}" >> $GITHUB_ENV
                  echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
                  echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

            - name: Grant Permission to Gradle
              run: chmod +x ./android/gradlew

            - name: Pack Data and Build Signed APK
              run: |
                  cd android
                  python pack_data.py
                  ./gradlew assembleRelease

            - name: Rename APK
              run: cp android/app/build/outputs/apk/release/app-release.apk EmeraldKnight.apk

            - name: Upload APK to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: EmeraldKnight.apk
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
