name: Build & Release Android APK

on:
    push:
        tags:
            - "v*" # 只有打 tag 时才运行
        branches:
            - android

permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: 17

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            - name: Decode Keystore
              run: |
                  echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.p12
                  echo "KEYSTORE_PATH=$(pwd)/my-release-key.p12" >> $GITHUB_ENV
                  echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
                  echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
                  echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

            - name: Grant Permission to Gradle
              run: chmod +x ./android/gradlew

            - name: Build Signed APK
              run: |
                  cd android
                  ./gradlew assembleRelease

            - name: Upload APK to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: android/app/build/outputs/apk/release/*.apk
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
