name: Game Test

on:
    # Runs on pushes targeting the default branch
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop

jobs:
    # Build job
    build:
        name: 测试代码并输出覆盖率
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  # Semantic version range syntax or exact version of a Python version
                  python-version: "3.12"
            - name: Install Coverage
              run: python -m pip install coverage
            - name: Test
              run: coverage run -m unittest discover -s script/test
            - name: Report coverage
              run: coverage report

    # # Deployment job
    # deploy:
    #     environment:
    #         name: github-pages
    #         url: ${{ steps.deployment.outputs.page_url }}
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:
    #         - name: Deploy to GitHub Pages
    #           id: deployment
    #           uses: actions/deploy-pages@v4
