name: Deploy to Web

on:
    push:
        branches:
            - master
            - web
    pull_request:
        branches:
            - master

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build_home:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Homepage with Jekyll
              uses: actions/jekyll-build-pages@v1
              with:
                  source: ./
                  destination: ./_site
    build_web:
        runs-on: ubuntu-latest
        steps:
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Build Web
              run: |
                  cd web
                  cp -r ../data ./public/data
                  npm install
                  npm run build

    upload:
        needs:
            - build_home
            - build_web
        runs-on: ubuntu-latest
        steps:
            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Move builds together
              run: |
                  mkdir _site/web
                  cp -r web/dist/* _site/web/

            - name: Upload built files
              uses: actions/upload-pages-artifact@v3
              with:
                  path: _site

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
