@startuml EmeraldKnight
title 翡翠骑士

!include EmeraldKnight_ch1.puml!0
!include EmeraldKnight_ch2.puml!0
!include EmeraldKnight_ch3.puml!0
!include EmeraldKnight_ch4.puml!0
!include EmeraldKnight_ch5.puml!0
!include EmeraldKnight_ch7.puml!0

@enduml
@startuml Ch1
title 翡翠骑士 第一章

!include EmeraldKnight-part.puml!0
@enduml
@startuml Ch2
title 翡翠骑士 第二章

!include EmeraldKnight_ch2.puml!0

class 2_0<<(S,Red)>>

2_0-->2_1
2_0-->2_2
2_0-->2_3
@enduml
@startuml Ch3
title 翡翠骑士 第三章

!include EmeraldKnight_ch3.puml!0

class 3_0<<(S,Red)>>

3_0-->3_1
3_0-->3_2
3_0-->3_3
3_0-->3_4
@enduml
@startuml Ch4
title 翡翠骑士 第四章

!include EmeraldKnight_ch4.puml!0

class 4_0<<(S,Red)>>

4_0-->4_1
4_0-->4_2
@enduml
@startuml Ch5
title 翡翠骑士 第五-六章

!include EmeraldKnight_ch5.puml!0

class 5_0<<(S,Red)>>

5_0-->5_1
5_0-->5_4
@enduml
@startuml Ch7
title 翡翠骑士 第七章

!include EmeraldKnight_ch7.puml!0


@enduml