
@startuml Ch2

!include head.puml

$step("银鳞村，图书馆","None",2)
$link_self($node_near(4),"魔法知识")
$link_self($node_near(5),"传说记载")
$link_self($node_near(6),"大陆历史")
$step("百羽镇")
$link_self($node_near(8),"（和奥利在一起）进树林")
$link_self($node_near(9),"（自己）进百羽镇")
$step("天使城，神殿","bruce")
$link_self($node_near(24),"（翡翠剑异变3次）","bruce")
$link_self($node_near(25),"（翡翠剑异变1次）")
$link_self($node(7,1),"开启翡翠暮光结局")
$step("黑暗吞食生命，光明消灭黑暗（知识+）")
$link_this($node_near(1))
$link_this($node_near(7),$choice_near(1,4),"研究昨天为什么迷路")
$step("精灵是大自然的孩子，也是生命的挚友（知识+）")
$link_this($node_near(1))
$link_this($node_near(7),$choice_near(1,4),"研究昨天为什么迷路")
$step("一千年前，黑暗力量也曾来袭过（知识+）")
$link_this($node_near(1))
$link_this($node_near(7),$choice_near(1,4),"研究昨天为什么迷路")
$step("翻出一份推论，涉及空间的禁咒级魔法会可能扭曲附近的空间（知识+）")
$link_self($node(3,2))
$step("植物在奥利的指挥下移动，分出一条路来，沿着那条路走进去，你看到了一棵参天大树，简直有龙骨雪山那么高。奥利说真的有那么高，问你想先去哪里")
$link_self($node_near(10),"黑暗力量")
$link_self($node_near(11),"四处逛逛")
$link_self($node_near(12),"（在奥利家见过箭）箭")
$step("遇到托马，他告诉你地图没有错，但你为什么会迷路，他也猜不出来")
$link_self($node_near(20),"（没看树）那我走了，去翻龙骨雪山")
$link_self($node_near(21),"（没看树）你还知道别的怪事吗")
$link_self($node_near(19),"（看树）你知道精灵吗")
$step("奥利带你去问生命之树，生命之树是大陆上第一棵树，已经活了很多很多年，你刚站到它面前，生命之树上忽然伸出一根树枝，拍了拍翡翠剑")
$link_self($node_near(13),"躲开")
$link_self($node_near(14),"不动")
$step("精灵族的栖息地是被称作“生命之树”的植物，高耸入云，精灵是树上结的果子，落地化为人形，有操控自然之力的能力")
$link_self($node_near(17),"自然之力？")
$link_self($node_near(18),"所以你不是人？")
$step("（奥利好感+3）那个徽记是他的精灵名，意为橄榄，敢说出去你就死定了")
$link_this($node_near(8))
$step("根本没用")
$link_this($node_near(14),$choice_near(10,2))
$step("（声望+2）生命之树把翡翠剑抽出来，说好久没见过它了")
$link_self($node_near(15),"上次见是什么时候")
$link_self($node_near(33),"（翡翠剑有异动）这把剑是不是有什么不同凡响的地方（智力+2）")
$step("上次见它，还是在阿宾的手里，你问阿宾是谁，生命之树告诉你是很多年前讨伐魔王的勇士，他是精灵族的朋友，从这里出发去翻越龙骨雪山，但再也没有回来")
$link_self($node_near(16),"道谢离开")
$step("你在精灵族休息了一夜，或许是生命的滋养，你感到自己充满精力")
$link_self($node(3,3),"沿阿宾的路前进")
$step("魔法师所谓的自然元素之一的生命，这种能力来自于生命之树，但因为黑暗力量的侵袭，他们已经若小了很多（知识+1）")
$link_this($node_near(10),$choice_near(11,3),"黑暗力量")
$step("奥利说我是半人，因为黑暗力量，生命之树几十年没结过果子了")
$link_this($node_near(10),$choice_near(11,3),"黑暗力量")
$step("绝迹很久了")
$link_this($node_near(9),"没看树")
$step("他问你问这个干什么，你说要去讨伐魔王，他劝你最好别去")
$link_self($node_near(22),"你还知道什么？")
$link_self($node_near(23),"不想说，我就不问了")
$step("今天上午有几个昨天去打猎的人回来，也说昨天莫名其妙地迷路了")
$link_this($node_near(20),$choice_near(9,1),"那我走了，去翻龙骨雪山")
$step("托马就是当年捡到翡翠剑的猎人，当时半空中有个黑茧，他用藤蔓够了一下，死了一大片植物，黑茧里绿光大盛，他再睁眼，剑就跌到了地上。（知识+3）")
$link_this($node_near(23),$choice_near(20,2),"不想说，我就不问了")
$step("你和托马分开，沿着原定路线向龙骨雪山前进")
$link_this($node(3,2),$choice_near(7,1))
$step("翡翠剑在你步入神殿的时候突然飞了起来，一剑刺进了神殿中央的石台，神殿祭司甘瑟走出来，问是怎么回事","bruce")
$link_self($node_near(26),"我也不知道")
$link_self($node_near(27),"（知识>5）这下面是不是有黑暗力量","bruce")
$step("你告诉守卫，是欧阿的长老团让你来这里问问翡翠剑的事，过了一会儿，祭司甘瑟走了出来")
$link_self($node_near(28),"我来是想了解一下翡翠剑")
$step("甘瑟看见翡翠剑，似乎明白了什么，但他没有告诉你")
$link_this($node_near(28),$choice_near(25,1),"我来是想了解一下翡翠剑")
$step("是的，石台下镇压的是天使出现的原因，一直封闭着，没有人打开过（智力+2）","bruce")
$link_this($node_near(28),$choice_near(25,1),"我来是想了解一下翡翠剑","bruce")
$step("翡翠剑是在天使城铸造的。工匠是矮人族，也有精灵、魔法导师和炼金师的参与，它有一个特别的功能，就是感应黑暗力量。剑柄上原本镶嵌着一个被称作剑心的宝石，可以把生命力量转换为光明。甘瑟不知道剑心是怎么制造的，也不知道它为什么会消失","bruce")
$link_self($node_near(29),"那你知道什么")
$link_self($node_near(30),"那谁会知道（智力+）","bruce")
$step("我知道谁知道")
$link_this($node_near(30),$choice_near(28,2),"那谁会知道")
$step("毁掉剑心的人一定知道，除此之外，就是上一任的翡翠剑主人，阿宾","bruce")
$link_self($node_near(31),"他还活着？","bruce")
$link_self($node_near(32),"这不是废话吗（智力-）")
$step("他死在了龙骨山脉里，甘瑟做过很多探查，大概划出了一个范围","bruce")
$link_self($node(3,4))
$step("甘瑟生气了，你还听不听")
$link_this($node_near(31),$choice_near(30,1),"他还活着？")
$step("是的，它是专为与魔王作战锻造的")
$link_this($node_near(15),$choice_near(14,1),"上次见是什么时候")

@enduml