@startuml Ch3

!include head.puml!0

$step("瑟尔指的路下面是一片峭壁，隐约能看见一些可以搭手的藤蔓","None",3)
$link_self($node_near(5),"爬（驯服度+）","sinestro")
$link_self($node_near(30),"不爬")
$step("你穿越森林、攀过悬崖，最终爬上了山脊，步入白雪覆盖的领域，令你惊讶的是，山里有一道烟正在升起")
$link_self($node_near(31),"去看看")
$link_self($node_near(41),"专心赶路")
$step("这条路很好走，近乎坦途，沿路生长着灌木和苔藓，完全没有走错的可能，你一路前行，看到了路边的石碑，了解了大陆历史（知识+2）")
$link_self($node_near(43),"捡龙牙")
$step("你踏出传送阵，手中的翡翠剑就嗡鸣起来，带你走到了一个雪堆，看来这就是阿宾的坟。","bruce")
$link_self($node_near(50),"先祭奠一下")
$link_self($node_near(51),"直接动手挖坟")
$step("你屡次尝试，越爬越高，但在几十米后，上方突然出现了一道很大的凹痕，无法继续上攀，周围又开始下雨，你只好爬进凹痕暂避。雨越下越大，你估计这几天都爬不了山了，山壁滑不溜秋，无可奈何之下，你只好决定在凹痕深处暂时扎营。迷迷糊糊间，似乎看到一个人影站在雨幕之前。","sinestro")
$link_self($node_near(6),"谁在那儿")
$link_self($node_near(7),"摸剑")
$step("没人回答，那个人四下看了看，叹了口气：“这么大雨，没法爬山了”")
$link_self($node_near(8),"观察他")
$link_self($node_near(9),"伸手拍拍")
$step("你摸了个空，忽然想不起把剑放在了哪儿，只好朝那个人走去。")
$link_this($node_near(6),$choice_near(5,1))
$step("这个人穿得很整洁，连绑腿护腕都一丝不苟，斗篷上满是晶亮的雨水。他脱下斗篷放在一边，露出腰间的长剑，坐下开始进食，你在他面前晃了晃，他果然看不见你")
$link_self($node_near(10),"继续观察")
$link_self($node_near(11),"寻找其他线索")
$step("你伸手去拍他，手却从他身体里穿了过去，你吃了一惊，打量四周，发现似乎比你进来前要干净许多，你记得进来时凹痕口有一棵大树，可当你看去，那里却只有几棵杂草")
$link_this($node_near(8),$choice_near(6,1))
$step("那个人吃完饭，从领口里拽出一条工艺粗糙的链子，上面却有一颗很漂亮的菱形绿宝石吊坠，他摸着吊坠，似乎想起了谁，露出一个笑容。你从没见过那个吊坠，却觉得有些熟悉，正当你苦苦思索的时候，一道鸟鸣声忽然响起，一只漆黑的大鸟钻进了凹痕，它有三只赤红的眼睛，一只脚，两条长长的尾羽，你从没见过这样的东西，可那个人却不显得惊讶，立刻拔剑攻了上去。经过一番战斗，他成功战胜了怪鸟，但怪鸟的爪钩钩断了他颈上的链子，那颗吊坠带着链子，掉下了峭壁，他怔怔地在凹痕边站着，雨始终没有停")
$link_self($node_near(12),"别人的记忆","sinestro")
$link_self($node_near(13),"你的梦境")
$step("你之前的营地完全不见踪影，抓着爬上来的藤蔓也仿佛只是你的错觉，你发现，离那个人越远，眼前的景色就越模糊不清，看来，那个人才是一切的关键")
$link_this($node_near(10),$choice_near(8,1))
$step("谁的记忆","sinestro")
$link_self($node_near(14),"那个人","sinestro")
$link_self($node_near(15),"翡翠剑")
$step("哪只鸟你完全不认识，不可能梦得这么清晰")
$link_this($node_near(16),$choice_near(14,1),"深入凹痕")
$step("（驯化度+2）那个人和瑟尔长得截然不同，但如果不考虑样貌，只从逻辑推断，这条路是瑟尔给你指的，他一定走过；手里拿的不是翡翠剑，因此不是上一位勇者；所以，这段记忆的主人只可能是以前的瑟尔","sinestro")
$link_self($node_near(16),"深入凹痕")
$step("不，幻觉里没有翡翠剑")
$link_this($node_near(16),$choice_near(14,1),"深入凹痕")
$step("凹痕越来越窄，但始终有路可走，一些很窄的地方残留着非天然的痕迹，这条路应该以前有人走过，你点着火把一路深入，到了一处吊桥遗址，吊桥已经朽败，完全不能借力")
$link_self($node_near(17),"找藤蔓")
$link_self($node_end(5),"直接跳")
$new_end(5,"END 05 笼中之鸟")
$step("你从凹痕外弄来藤蔓，决定自造吊索，你抓起一块石头，忽然发现下面有一封信。信写给一个名为阿宾的人，告诉他自己遗失了阿琳送的吊坠，根据预言，自己这次讨伐黑暗力量，将再也回不来了，又详细描述了吊坠遗失时的情形，希望阿宾可以找到它。署名则是，瑟尔。你收起信，利用藤蔓制成的吊索，成功到达了另一端")
$link_self($node_near(18),"继续前进")
$step("沿着山路一直走，穿过一排藤蔓，炫目的光立刻淹没了你，你眼前是茫茫白雪，你已经到了龙骨雪山，翡翠剑忽然嗡鸣起来，你按照它指引的方向，绕过岩石、树木，来到了一处雪堆。翡翠剑哀鸣着，你猜，这是它上一任主人的埋骨之地","sinestro")
$link_self($node_near(19),"瑟尔？")
$link_self($node_near(20),"阿宾？")
$link_self($node_near(21),"阿琳？","sinestro")
$step("（智力-1）我怎么会是瑟尔，翡翠剑都不认得他。我的名字是阿宾")
$link_self($node_near(27),"我看到了他的信")
$link_self($node_near(22),"我以为他会在山上")
$step("年轻的勇士，你怎么会知道我的名字？根据信上的内容猜的，你不是死了吗？有时，死亡并不意味着终结。")
$link_self($node_near(22),"瑟尔是你什么人")
$link_self($node_near(21),"阿琳是谁")
$step("（好感度+1）她已久不在人世了，你怎么会知道她？","sinestro")
$link_self($node_near(27),"如实告知","sinestro")
$link_self($node_near(28),"含糊过去")
$step("你认得他？")
$link_self($node_near(23),"坦诚相告")
$link_self($node_near(24),"我还要脸")
$link_self($node_near(27),"捡到了他的信")
$step("他曾经是我最好的朋友，也是前去讨伐魔王的勇者，预言上说，如果他丢失了那枚吊坠，他就会被黑暗吞没。那我睡的是谁？或许预言错了，或许被黑暗吞没，不只有死亡一种可能","sinestro")
$link_self($node_near(25),"他是我的敌人？")
$link_self($node_near(26),"（驯化度=7）他还可以被拯救吗","sinestro")
$step("我不明白他要对你做什么，但是，当心")
$link_self($node_near(23),"怎么说？")
$step("没错。在战斗时，你最好忘记你与他认识，因为他是不会在意的，还有一件事")
$link_this($node_near(29),$choice_near(28,1),"请说")
$step("（好感度+2）我不知道，我只是个死人。剑在你手中，路在你脚下，未来世界什么样子，都在你的一念之间，还有一件事","sinestro")
$link_this($node_near(29),$choice_near(28,1),"请说")
$step("原来如此，原来他还留了一封信。我是阿宾，也是翡翠剑的第一任主人。阿琳……是我妹妹。我那个年代，黑暗力量侵袭，她的未婚夫瑟尔，尽管有着不祥的预言，但还是作为勇者出发了。他没有回来，我们在他经过的峭壁下捡到了那枚吊坠。我决定继续他未竟的事业，因为黑暗在变强，获得了很多支持，也就有了翡翠剑，阿琳为了确保胜利，用自己的生命和灵魂，为我铸就了翡翠剑的剑心，可，我却辜负了她，不仅自己战败身死，连剑心也毁了","sinestro")
$link_self($node_near(23),"信上的瑟尔又是谁？","sinestro")
$step("你不想说，我不强求。我是阿宾，翡翠剑的第一任主人。你出现在这里，是为了去讨伐魔王吧。抱歉，我战败了，给不了你什么帮助，只有一件事能告诉你")
$link_self($node_near(29),"请说")
$step("翡翠剑的本质是勇气，持剑的时候，永远不要忘记这一点")
$link_self($node(4,1),"告辞离开")
$step("你担心这条路可能已经没法走了，沿着山脉前行，走上了原定的翻山之路")
$link_self($node_near(2),"出发")
$step("你朝烟雾升起的方向走去，在一处山坳，发现了一座林中小屋，一个人恰好从小屋里走出来，竟然是卡萝，她在你之后出发，追查一支很奇怪的箭，与精灵族相识，在这里学习炼金术（知识+3）")
$link_self($node_near(32),"为什么选这儿")
$link_self($node_near(33),"这里安全吗")
$link_self($node_near(34),"可以参观吗")
$step("交通便利")
$link_this($node_near(31))
$link_this($node_near(49),$choice_near(31,4),"有什么能帮忙的")
$step("很安全，卡萝比你想得厉害")
$link_this($node_near(31))
$link_this($node_near(49),$choice_near(31,4),"有什么能帮忙的")
$step("获得通讯水晶")
$link_this($node_near(31))
$link_this($node_near(49),$choice_near(31,4),"有什么能帮忙的")
$step("处理材料")
$link_self($node_near(36),"处理羽毛")
$link_self($node_near(36),"处理金属")
$link_self($node_near(36),"处理骨头")
$link_self($node_near(37),"附魔翅膀")
$link_self($node_near(37),"附魔身体")
$link_self($node_near(38),"成功")
$link_self($node_near(39),"失败")
$step("怎么处理")
$link_self($node_near(35),"（羽毛）清洁")
$link_self($node_near(35),"（金属）熔化")
$link_self($node_near(35),"（骨头）粉碎")
$step("什么属性")
$link_self($node_near(35),"（翅膀）风属性")
$link_self($node_near(35),"（身体）水属性")
$step("一滴血（获得坐骑，智力+3）")
$link_self($node_near(40),"去黑暗领域怎么走")
$step("卡萝嫌弃")
$link_this($node_near(40),$choice_near(38,1),"去黑暗领域怎么走")
$step("先去哥谭")
$link_self($node(5,1),"第五章 孤城")
$step("积雪不深，你行走时发现雪下面有东西")
$link_self($node_near(42),"捡")
$link_self($node_near(43),"不捡")
$step("一根白色的锥形棍子")
$link_self($node_near(43))
$step("你发现一个奇怪的雪洞")
$link_self($node_near(44),"进")
$link_self($node_near(45),"不进")
$step("有野果，吃得很饱")
$link_self($node_near(45))
$step("你走在路上，忽然被什么绊了一下，定睛一看，雪地里有着一段雪白的骨头，雪地起伏，似乎是一具很大的尸骨，你沿着尸骨前进，到了一处突出的山头，地势陡峭")
$link_self($node_near(46),"（吃饱了且有龙牙）")
$link_self($node_near(47),"（吃饱了但没龙牙）")
$link_self($node_near(48),"（没吃饱）")
$step("你爬上了山头，脚下忽然开始震动，好一阵子才平息下来，你发现自己站在雪白的尸骨上，脚下，似乎是一颗头颅，脑袋里，少了一颗牙，你把白色锥形棍装进孔洞里，尸骨闪了闪，眼睛的空洞里有绚烂的光放出，你看到了三百年前的大战画面，一只冰蓝色的巨龙用尽最后的力量立起一条雄伟的山脉，隔绝了大陆两侧，自己力竭倒地，三百年的时光倏忽而过，你仿佛看到黑暗那边有一座城（智力+1）")
$link_self($node(5,1),"第五章 孤城")
$link_self($node(4,2),"第四章 远方")
$step("你借助好视野，画了一幅地图，向被黑暗笼罩的地方出发")
$link_this($node(4,2),$choice_near(46,2),"第四章 远方")
$step("你想爬，但却没有足够的体力，只好放弃了")
$link_self($node(4,1))
$step("新作品")
$link_self($node_near(35),"开始")
$step("雪堆竟然回应了，你吃了一惊，他的灵魂没有消散，向你讲述了他和魔王的故事，但死后的事他不知道，因此也不知道翡翠剑后来怎样，或许他的尸体会记得，于是你在他的同意下刨开雪堆（知识+）")
$link_this($node_near(52),$choice_near(4,3),"回溯")
$step("你刨开雪堆，仿佛听到了一声久远之前的叹息")
$link_this($node_near(52),$choice_near(4,3),"回溯")
$step("你对着尸骨进行回溯")
$link_self($node_near(53),"头骨")
$link_self($node_near(54),"胸骨")
$link_self($node_near(55),"臂骨")
$link_self($node_near(56),"脊椎")
$link_self($node_near(57),"（可选）破烂披风")
$step("剑心的铸造")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("决战，阿宾被瑟尔掏出心脏")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("阿宾和瑟尔练剑，瑟尔的弱点")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("阿宾记忆里的小镇")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("天使城的传说（知识+）","bruce")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("下一步计划","bruce")
$link_self($node_near(59),"讨伐魔王")
$link_self($node_near(60),"哥谭（不认识布鲁斯）")
$link_self($node_near(61),"哥谭（认识布鲁斯）","bruce")
$step("前方被山挡住了，从哪边绕")
$link_self($node(4,1),"左")
$link_self($node_near(41),"右")
$step("你从山顶出发，路上不慎滑了一跤，在雪地里滑出去很远，最后撞上树，灰头土脸地爬起来，已经在一座山谷里了，你发现附近有一条被踩出来的小路，你决定去碰碰运气")
$link_self($node_near(62),"向左")
$link_self($node_near(63),"向右")
$step("你忽然想起，布鲁斯曾说过他是哥谭人，想起布鲁斯，你忽然对他和哥谭感到万分好奇，晚上你找了个避风的山洞露营，外面忽然刮起风雪，翡翠剑旁的雪融化，留下一个菱形的坑。","bruce")
$link_self($node_near(68),"出去看看","bruce")
$link_self($node_near(69),"好好休息")
$step("你走到了一处路口，面前有两条岔路")
$link_self($node_near(64),"向左")
$link_self($node_near(65),"向右")
$link_self($node_near(63),"（第一次来）回头")
$step("你在路边看到了一块大石，上面刻了去哥谭的路，三岔路口右转，溪边向上游前进，森林前的大路朝山上走")
$link_self($node_near(62))
$step("你迷路在了山林里，快要饿死的时候，遇到了猎人，对方把你带到了哥谭")
$link_self($node(5,1))
$step("走到了溪边")
$link_self($node_near(66),"向上游")
$link_self($node_near(64),"向下游")
$link_self($node_near(64),"涉水走对岸的路")
$step("走到了森林边，小溪是从森林里流出来的，森林前有一条宽敞的路，左侧通向一片平原，右侧通向山上")
$link_self($node_near(64),"进森林")
$link_self($node_near(67),"左转")
$link_self($node(5,1),"右转（智力+2）")
$step("你走到了一座冰湖，饱览了冰天雪地的奇异风景")
$link_self($node(5,1))
$step("你在风雪中仿佛看到一个漆黑的人影，走近了却又见不到人，你无功而返，在山洞前看到了几个脚印，你小心地持剑走了进去，却发现这不是你的山洞。你拐过一个弯，对上了一双深蓝的眼睛","bruce")
$link_self($node_near(70),"（智力=3）布鲁斯？（好感度+2）","bruce")
$link_self($node_near(71),"防御")
$link_self($node_near(72),"进攻（好感度-3）")
$step("你在风雪中度过一夜")
$link_this($node_near(60),$choice_near(58,2))
$step("哈尔？你怎么跑到这儿来的。你告诉他自己准备去哥谭，刚刚翡翠剑有反应，你担心是黑暗力量作祟","bruce")
$link_this($node_near(73),$choice_near(68,4))
$step("对方并没有进攻，你与他对视片刻：“布鲁斯？”")
$link_this($node_near(73),$choice_near(68,4))
$step("对方和你过了几招，你把他逼到墙边，听到对方念了几个你听不懂的词，你忽然动弹不得，听到他说：“你有毛病吗，勇者？”")
$link_this($node_near(73),$choice_near(68,4))
$step("一只鹰魔跨越边界上了龙骨雪山，布鲁斯来追杀它","bruce")
$link_self($node_near(74),"鹰魔是什么","bruce")
$link_self($node_near(75),"需要我帮忙吗")
$step("（知识+1）","bruce")
$link_this($node_near(75),$choice_near(73,2),"","bruce")
$step("布鲁斯静静地扫视了你一下，说不用，等风雪停了他自己可以，你待在山洞里就行","bruce")
$link_self($node_near(76),"坚持帮忙")
$link_self($node_near(77),"不再插手")
$link_self($node_near(77),"假意同意","bruce")
$step("（好感度-）布鲁斯表示你要找死他不管")
$link_this($node_near(78),$choice_near(75,4),"等雪停")
$step("布鲁斯冷淡地朝你点点头","bruce")
$link_this($node_near(78),$choice_near(75,4),"等雪停","bruce")
$step("风雪停下时天还没亮，布鲁斯从口袋里掏出一个吊坠戴在脖子上，一颗拇指大的珍珠在他的魔法下发出明亮的光，他看着你的眼神，也给了你一个，转身走出了山洞","bruce")
$link_self($node_near(79),"（假意答应）稍后跟上","bruce")
$link_self($node_near(80),"（坚持）跟上")
$link_self($node_near(81),"原地等候")
$step("你跟出去的时候布鲁斯已经在和鹰魔交战了，他的剑术很好，但鹰魔的速度实在太快，因此他也多少有些应付不过来，你冲上去帮他，他不怎么领情，并肩作战，成功收拾了鹰魔（好感度+3）","bruce")
$link_this($node(5,1),$choice_near(78,4))
$step("你跟在布鲁斯身后，没走出多远就被鹰魔突袭了。你从没应付过这种局面，险象环生，布鲁斯非常生气，最后你们杀掉了鹰魔，你也挂了彩，没受伤的他把你狠狠训了一顿")
$link_this($node(5,1),$choice_near(78,4))
$step("过了几个小时，布鲁斯带伤归来，他有一道很大的伤口，并不深，但还是流了不少血，你给他包扎，他虽然拒绝，但无力反抗。最后他很费劲地说了谢谢（好感+）")
$link_this($node(5,1),$choice_near(78,4),"","bruce")

@enduml