@startuml Ch7

!include head.puml!0
$step("你在天使城里闲逛，忽然听到了竖琴声，你循声走进酒馆，吟游诗人唱着一个故事，魔王隐瞒身份与勇者相遇，二人成为了朋友。二人一路同行，勇者明知那是敌人，却爱上了魔王；魔王也爱上了勇者",None,7)
$link_self($node_end(19),"打断他")
$new_end(19,"END 19 视差未来")
$link_self($node_near(2),"继续听")
$step("他们一直走到魔王的宫殿，图穷匕见，魔王没有抵抗，死在了勇者剑下。心中矛盾的勇者被魔王的力量侵蚀，成为了新的魔王")
$link_this($node_end(19),$choice_near(1,1))
$link_self($node_near(3),"继续听")
$step("新的魔王拥有双倍的力量，摧枯拉朽般战胜了人类，黑暗笼罩了全大陆。故事告一段落，吟游诗人看向你，想问问勇者有什么看法")
$link_self($node_end(19),"瞎几把扯")
$link_self($node_near(5),"不就是个悲剧")
$link_self($node_near(4),"你跑调了")
$step("谁问你这个了！")
$link_this($node_near(5))
$step("你找了个清净地方，和凯尔仔细分析了“魔王隐瞒身份遇到勇者”的可能性，结论是其概率实在低到不值得认真对待。你去神殿问翡翠剑的事，发现天使雕像成了凯尔的模样")
$link_self($node_near(6),"（知识>5）那个故事真的发生了")
$link_self($node_near(8),"（认识布鲁斯但知识不足）你是什么人")
$link_self($node_near(9),"你是天使？")
$step("凯尔带你走进神殿，神殿中央是一个龟裂的黑色石台，那是穿越时间留下的痕迹。凯尔来自你成为魔王的未来，但你却并不认识魔王，你唯一认识的是布鲁斯，出于保险起见，你决定和凯尔一起上路")
$link_self($node_end(20),"讨伐魔王")
$new_end(20,"END 20 未曾设想")
$link_self($node_near(7),"先找找布鲁斯是谁")
$step("你们查到了哥谭的信息，确定布鲁斯并不是魔王。你和凯尔在一起，对改变未来充满信心，你们走出神殿，一只老鼠跑过，凯尔拔出剑去打，半天都没打到。你把老鼠斩于剑下，凯尔尴尬地解释，他并不懂得战斗")
$link_this($node_end(21),$choice_near(8,1))
$new_end(21,"END 21 破晓曙光")
$step("凯尔是来阻止你的，你不置可否，和凯尔打了一架，轻松取胜，凯尔甚至没练过剑的样子")
$link_self($node_end(21),"你这样，来阻止我？")
$step("不，凯尔只是个来自你成为魔王的未来的普通人，路过神殿门口，被甘瑟抓了壮丁")
$link_this($node_end(21),$choice_near(8,1))
@enduml