@startuml Ch1

!include head.puml

$step("游戏开始","None",1)
$link_self($node_near(2),"继续前进","bruce")
$link_self($node_near(3),"转头回去")
$link_self($node_near(4),"原地睡一觉","sinestro")
$step("见到树上奇怪的影子，翡翠剑上的孔洞发烫，警惕着前方的风险")
$link_self($node_near(5),"追上去","bruce")
$link_this($node_near(3),$choice_near(1,2),"转头回去")
$step("渐渐找回了路，在夜晚的大树上见到了脚印")
$link_self($node_near(6),"原地蹲守")
$link_self($node_near(7),"不关我事")
$link_self($node_near(8),"爬上去")
$step("醒来身边有一团篝火，还有一个人，嘲讽你在野外睡觉都不点火","sinestro")
$link_self($node_near(9),"呛回去")
$link_self($node_near(10),"谢谢你","sinestro")
$link_self($node_near(11),"你哪位")
$step("你追着古怪的阴影一路前进，一直到一处深邃的阴影，一片叶子恰好落在翡翠剑的孔洞上，瞬间燃起了火","bruce")
$link_self($node_near(12),"直接进去")
$link_self($node_near(13),"四处看看（知识+）","bruce")
$step("你在隐蔽处等到天亮，终于听见声响，一个身影从岩缝里钻出来，青苔在他挥手间盖住了脚印，你也在这个时候看清了他的脸，是奥利。你回了小镇。")
$link_self($node_near(52),"去找奥利")
$link_self($node_near(18),"去找卡萝")
$step("你回了小镇，深夜街上空无一人，但有座房子依然亮着灯，是巴里家")
$link_self($node_near(14),"去敲门（知识+2）")
$link_self($node_near(17),"回家睡觉")
$step("摔晕了，醒来已经回到了小镇，巴里说是奥利把你送回来的")
$link_self($node_near(16),"找人带路去龙骨雪山")
$link_this($node_near(52),$choice_near(6,1),"去见他")
1_8-->1_16:1-8-2\n找人带路去龙骨雪山
$step("驯化度-")
$link_this($node_near(11),$choice_near(4,3),"你哪位")
$step("好感度+","sinestro")
$link_this($node_near(11),$choice_near(4,3),"你哪位","sinestro")
$step("他自称瑟尔。他问你是干嘛的，你告诉他你是讨伐魔王的勇者，他问你为什么要讨伐魔王","sinestro")
$link_self($node_near(55),"为了出名")
$link_self($node_near(56),"他是全大陆的威胁")
$link_self($node_near(57),"我想做点什么","sinestro")
$step("从黑洞里进去，是一个隧道，石壁上长的晶石发着冷白的光，你一路前进，晶石颜色愈发五花八门起来，有一些已经落到了地上，你准备捡一块","bruce")
$link_self($node_near(20),"捡块红的")
$link_self($node_near(21),"捡块蓝的")
$link_self($node_near(22),"捡块紫的")
$link_self($node_near(23),"捡块绿的","bruce")
$step("你绕着黑洞走了走，在一棵树上发现了一个刀刻般的痕迹，痕迹很新，好像才刻下没多久。","bruce")
$link_this($node_near(12),"","","bruce")
$step("巴里用鹅毛笔在羊皮纸上画着些什么，见到你很惊讶，问你怎么回来了")
$link_self($node_near(47),"路上迷路了")
$link_self($node_near(48),"想你了啊（好感度+）")
$link_self($node_near(49),"后悔了")
$step("我再给你一次机会")
$link_this($node_near(19),$choice_near(17,2))
$step("附近有几个小镇，去哪里问路")
$link_self($node(2,1),"河流上游的银鳞村")
$link_self($node(2,2),"沿大路走，树林里的百羽镇")
$step("你还要继续冒险吗")
$link_self($node_end(1),"不了，再见")
$new_end(1,"END 01 无事发生")
$link_self($node_near(19),"当然要啊")
$step("你问卡萝还记不记得那棵大树，有没有看到过什么奇怪的东西，卡萝是炼金术师，她说，捡到了一支箭（知识+3）")
$link_this($node_near(52),$choice_near(6,1),"去找奥利")
$step("那你接下来要做什么")
$link_this($node_near(16),$choice_near(8,1))
$link_this($node_near(15),$choice_near(19,1))
$step("火属性晶石")
$link_this($node_near(24),$choice_near(12,0),"继续前进")
$step("水属性晶石")
$link_this($node_near(24),$choice_near(12,0),"继续前进")
$step("空间属性晶石")
$link_this($node_near(24),$choice_near(12,0),"继续前进")
$step("生命属性晶石","bruce")
$link_this($node_near(24),$choice_near(12,0),"继续前进","bruce")
$step("继续前进，周围的晶石越来越多，你眼前一亮，走进了一间屋子，似乎是一间魔法师的书房。书房另一端，有一扇门","bruce")
$link_self($node_near(25),"书架","bruce")
$link_self($node_near(26),"挂毯")
$link_self($node_near(27),"卷轴")
$link_self($node_near(28),"墙上")
$link_self($node_near(29),"直接出门（智力-2）")
$step("光明符文","bruce")
$link_this($node_near(29),$choice_near(24,0),"","bruce")
$step("黑暗符文")
$link_this($node_near(29),$choice_near(24,0))
$step("大地符文")
$link_this($node_near(29),$choice_near(24,0))
$step("雷霆符文")
$link_this($node_near(29),$choice_near(24,0))
$step("你走出去，一步踏出，却看不到路。周围是一片无边无际的星空，转身，门却已经不见了。你只能往前走。隐约似乎看到了一个黑影","bruce")
$link_self($node_near(30),"追上去")
$link_self($node_near(34),"光明符文","bruce")
$step("追了两步就找不到了")
$link_this($node_near(39))
$step("你四处乱走，突然听到一声脆响，星空碎裂，你发现自己站在湖边。一个黑影划过你的眼角，转瞬消失在了森林里。")
$link_self($node_near(32),"追")
$link_self($node_near(33),"不追")
$step("追不上，你又累又饿，回了湖边")
$link_this($node_near(33),$choice_near(31,2))
$step("你在湖边略作休整，沿着水路出去，发现自己到了银鳞村。")
$link_this($node(2,1),$choice_near(16,1))
$step("是一个披着漆黑斗篷的人，他朝你走过来","bruce")
$link_self($node_near(35),"这是哪里")
$link_self($node_near(36),"你是谁")
$step("黑暗法师塔遗迹")
$link_this($node_near(37),$choice_near(34,0),"这是什么地方")
$link_this($node_near(36))
$step("和你一样的人")
$link_this($node_near(37),$choice_near(34,0),"这是什么地方")
$link_this($node_near(35))
$step("这里是一个法阵，已经被黑暗力量浸染，要出去，需要毁掉阵眼。","bruce")
$link_self($node_near(38),"你能做到？")
$link_self($node_near(39),"我能怎么帮你？（好感+1）","bruce")
$step("他再没搭理过你（好感-5）")
$link_self($node_near(31))
$step("找不对劲的地方","bruce")
$link_self($node_near(40),"（知识>=1）脚下踢到了一个黑漆漆的球形","bruce")
$link_self($node_near(31),"知识不足")
$step("你观察了这个球","bruce")
$link_self($node_near(41),"有生命晶石","bruce")
$link_self($node_near(45),"没有生命晶石，见到布鲁斯")
$link_self($node_near(31),"没有生命晶石也没见到布鲁斯")
$step("你刚想叫他过来，口袋里的晶石却发出了耀眼的绿光，自行飞出，落进了原本大小不合适的翡翠剑的孔洞。你挥动翡翠剑，打碎了晶石。星空随之碎裂。","bruce")
$link_self($node_near(44),"（好感+4）没见到布鲁斯")
$link_self($node_near(46),"（好感+10）","bruce")
$step("他给你介绍了法师塔废墟与黑暗力量的关系。（知识+5）","bruce")
$link_this($node_near(43),$choice_near(41,2),"问他的名字","bruce")
$step("他叫布鲁斯，是哥谭人，但你不知道哥谭在哪儿，场面一度十分尴尬。他说，要想多知道翡翠剑的事，可以去天使城。你告别了他，踏上去天使城的路。","bruce")
$link_this($node(2,3),$choice_near(16,3),"海边的天使城","bruce")
$step("你发现自己身处湖边，一个黑影划过眼角")
$link_this($node_near(31))
$step("你叫他过来，他让你走远些，用飞镖打碎的晶石，星空随之碎裂。他向你告别，你才想起还不知道他的名字，你大喊自己的名字，不知道他听没听见。（好感+2）")
$link_this($node_near(33),$choice_near(31,2),"不追")
$step("见到布鲁斯","bruce")
$link_this($node_near(42),$choice_near(41,1),"先问问他法师塔的事","bruce")
$link_this($node_near(43),$choice_near(41,2),"问他的名字")
$step("长老团给的地图不准，你找不到方向，担心越错越远，就回来了，巴里提议去银鳞村找人问路")
$link_this($node(2,1),$choice_near(16,1))
$step("他笑着说你别闹了，说正经的呢")
$link_this($node_near(47),$choice_near(14,1))
$step("巴里有些担心，问你为什么")
$link_self($node_end(1),"怕自己不够强")
$link_self($node_near(50),"（孔洞发烫）知道的太少，准备去找长老团")
$link_self($node_near(51),"（孔洞发烫）知道的太少，有个猜想要去百羽镇查证（知识+1）")
$step("去找长老团询问翡翠剑的秘密，长老团让你去天使城（知识+3）")
$link_this($node(2,3),$choice_near(49,1))
$step("去百羽镇")
$link_this($node(2,2),$choice_near(16,2))
$step("奥利不在家，他家里有做了一半的箭支")
$link_self($node_near(53),"（看到卡萝的箭）")
$link_self($node_near(54),"在屋里等他回来")
$step("仔细看，虽然和那支材料不同，但一些细节上的处理却非常相似（知识+1）")
$link_this($node_near(54),$choice_near(52,2))
$step("四处看看，发现一些端倪，等奥利回来，聊了聊，他带你去百羽镇")
$link_this($node(2,2),$choice_near(16,2))
$step("（好感度-）我希望自己死后几十几百年，依然有人记得我的名字")
$link_this($node_near(58),$choice_near(11,4))
$step("生在其中，无处可躲，为什么不直面未来？")
$link_this($node_near(58),$choice_near(11,4))
$step("（驯化度+）一辈子只有这么长，不如拿来做点别人做不了的事","sinestro")
$link_this($node_near(58),$choice_near(11,4),"sinestro")
$step("柴火突然炸了，把瑟尔吓了一跳","sinestro")
$link_self($node_near(59),"（驯化度>=0）你就这么在野外点火的？","sinestro")
$link_self($node_near(60),"这点胆子，还敢在树林里过夜？")
$link_self($node_near(61),"（好感度>=0）\n有点可爱")
$step("（驯化度++）他没呛声","sinestro")
$link_this($node_near(62),$choice_near(58,4),"sinestro")
$step("（驯化度-）与你何干")
$link_this($node_near(62),$choice_near(58,4))
$step("（好感度-）他问你是不是疯了")
$link_this($node_near(62),$choice_near(58,4))
$step("你把柴火重新收拾了一下，到了后半夜，突然感到不大对劲，瑟尔眼睛泛着金光，和你打了一架，好不容易把他制服","sinestro")
$link_self($node_near(63),"（好感度>0或驯化度>0）","sinestro")
$link_self($node_near(64),"（都<0）把他制住")
$step("瑟尔醒来，问你要不要上他","sinestro")
$link_self($node_near(72),"答应","sinestro")
$link_self($node_end(3),"拒绝")
$new_end(3,"END 03 宁死不屈")
$step("失败，他一下子挣脱了你的控制，不知是不是你的错觉，那一瞬间他的身体似乎变成了烟雾。天亮后你继续前进，发现自己到了百羽镇附近，反倒还沿着你原定规划的路线前进")
$link_self($node_near(65),"进去补给一下")
$link_self($node_near(66),"继续前进")
$step("你听说百羽镇昨晚有人失踪了")
$link_this($node_near(66),$choice_near(64,2),"继续前进")
$step("你又遇到了瑟尔")
$link_self($node_near(67),"（去了百羽镇）")
$link_self($node_near(68),"邀请他一起上路")
$step("你问失踪的人，和你有关吗？他痛快承认")
$link_self($node_near(69),"人在哪儿")
$link_self($node_near(70),"你为什么要抓人")
$step("你们一起走了一段，路边窜出一只兔子撞到他腿上，被黑暗力量缠绕，活活窒息而死")
$link_this($node_near(71),$choice_near(67,3))
$step("回家了，也死了")
$link_this($node_near(71),$choice_near(67,3))
$step("饿了")
$link_this($node_near(71),$choice_near(67,3))
$step("你到底什么来头，他说，你也猜到了吧，我是你要杀的魔王啊")
$link_self($node_end(2),"和他战斗")
$new_end(2,"END 02 出师未捷")
$step("第一步")
$link_self($node_near(73),"先亲")
$link_self($node_near(73),"先摸（评分+2）","sinestro")
$step("第二步")
$link_self($node_near(74),"按地上（评分+3）","sinestro")
$link_self($node_near(74),"按墙上")
$step("第三步")
$link_self($node_near(75),"里面（评分+5）","sinestro")
$link_self($node_near(75),"外面")
$step("做完了")
$link_self($node_near(76),"（10分）好评（好感++）","sinestro")
$link_self($node_near(77),"（5-9分）中评")
$link_self($node_end(4),"（0-4分）差评")
$new_end(4,"END 04 牡丹花下")
$step("他说下次再见，你肩上的牙印突然有点烫","sinestro")
$link_self($node_near(78),"还有下次？")
$link_self($node_near(79),"下次是什么时候")
$link_self($node_near(80),"我怎么联系你","sinestro")
$step("做完他就把你踹一边了，天亮后你到了百羽镇")
$link_this($node(2,2),$choice_near(16,2))
$step("（驯服-）对")
$link_this($node_near(81),$choice_near(76,4))
$step("到时候你就知道了")
$link_this($node_near(81),$choice_near(76,4))
$step("（驯服+，好感+）你不能","sinestro")
$link_this($node_near(81),$choice_near(76,4))
$step("你顺口问了一句，瑟尔给你指了翻越龙骨雪山的路，你决定跟着走","sinestro")
$link_self($node(3,1))

@enduml
@startuml Ch2

!include head.puml

$step("银鳞村，图书馆","None",2)
$link_self($node_near(4),"魔法知识")
$link_self($node_near(5),"传说记载")
$link_self($node_near(6),"大陆历史")
$step("百羽镇")
$link_self($node_near(8),"（和奥利在一起）进树林")
$link_self($node_near(9),"（自己）进百羽镇")
$step("天使城，神殿","bruce")
$link_self($node_near(24),"（翡翠剑异变3次）","bruce")
$link_self($node_near(25),"（翡翠剑异变1次）")
$link_self($node(7,1),"开启翡翠暮光结局")
$step("黑暗吞食生命，光明消灭黑暗（知识+）")
$link_this($node_near(1))
$link_this($node_near(7),$choice_near(1,4),"研究昨天为什么迷路")
$step("精灵是大自然的孩子，也是生命的挚友（知识+）")
$link_this($node_near(1))
$link_this($node_near(7),$choice_near(1,4),"研究昨天为什么迷路")
$step("一千年前，黑暗力量也曾来袭过（知识+）")
$link_this($node_near(1))
$link_this($node_near(7),$choice_near(1,4),"研究昨天为什么迷路")
$step("翻出一份推论，涉及空间的禁咒级魔法会可能扭曲附近的空间（知识+）")
$link_self($node(3,2))
$step("植物在奥利的指挥下移动，分出一条路来，沿着那条路走进去，你看到了一棵参天大树，简直有龙骨雪山那么高。奥利说真的有那么高，问你想先去哪里")
$link_self($node_near(10),"黑暗力量")
$link_self($node_near(11),"四处逛逛")
$link_self($node_near(12),"（在奥利家见过箭）箭")
$step("遇到托马，他告诉你地图没有错，但你为什么会迷路，他也猜不出来")
$link_self($node_near(20),"（没看树）那我走了，去翻龙骨雪山")
$link_self($node_near(21),"（没看树）你还知道别的怪事吗")
$link_self($node_near(19),"（看树）你知道精灵吗")
$step("奥利带你去问生命之树，生命之树是大陆上第一棵树，已经活了很多很多年，你刚站到它面前，生命之树上忽然伸出一根树枝，拍了拍翡翠剑")
$link_self($node_near(13),"躲开")
$link_self($node_near(14),"不动")
$step("精灵族的栖息地是被称作“生命之树”的植物，高耸入云，精灵是树上结的果子，落地化为人形，有操控自然之力的能力")
$link_self($node_near(17),"自然之力？")
$link_self($node_near(18),"所以你不是人？")
$step("（奥利好感+3）那个徽记是他的精灵名，意为橄榄，敢说出去你就死定了")
$link_this($node_near(8))
$step("根本没用")
$link_this($node_near(14),$choice_near(10,2))
$step("（声望+2）生命之树把翡翠剑抽出来，说好久没见过它了")
$link_self($node_near(15),"上次见是什么时候")
$link_self($node_near(33),"（翡翠剑有异动）这把剑是不是有什么不同凡响的地方（智力+2）")
$step("上次见它，还是在阿宾的手里，你问阿宾是谁，生命之树告诉你是很多年前讨伐魔王的勇士，他是精灵族的朋友，从这里出发去翻越龙骨雪山，但再也没有回来")
$link_self($node_near(16),"道谢离开")
$step("你在精灵族休息了一夜，或许是生命的滋养，你感到自己充满精力")
$link_self($node(3,3),"沿阿宾的路前进")
$step("魔法师所谓的自然元素之一的生命，这种能力来自于生命之树，但因为黑暗力量的侵袭，他们已经若小了很多（知识+1）")
$link_this($node_near(10),$choice_near(11,3),"黑暗力量")
$step("奥利说我是半人，因为黑暗力量，生命之树几十年没结过果子了")
$link_this($node_near(10),$choice_near(11,3),"黑暗力量")
$step("绝迹很久了")
$link_this($node_near(9),"没看树")
$step("他问你问这个干什么，你说要去讨伐魔王，他劝你最好别去")
$link_self($node_near(22),"你还知道什么？")
$link_self($node_near(23),"不想说，我就不问了")
$step("今天上午有几个昨天去打猎的人回来，也说昨天莫名其妙地迷路了")
$link_this($node_near(20),$choice_near(9,1),"那我走了，去翻龙骨雪山")
$step("托马就是当年捡到翡翠剑的猎人，当时半空中有个黑茧，他用藤蔓够了一下，死了一大片植物，黑茧里绿光大盛，他再睁眼，剑就跌到了地上。（知识+3）")
$link_this($node_near(23),$choice_near(20,2),"不想说，我就不问了")
$step("你和托马分开，沿着原定路线向龙骨雪山前进")
$link_this($node(3,2),$choice_near(7,1))
$step("翡翠剑在你步入神殿的时候突然飞了起来，一剑刺进了神殿中央的石台，神殿祭司甘瑟走出来，问是怎么回事","bruce")
$link_self($node_near(26),"我也不知道")
$link_self($node_near(27),"（知识>5）这下面是不是有黑暗力量","bruce")
$step("你告诉守卫，是欧阿的长老团让你来这里问问翡翠剑的事，过了一会儿，祭司甘瑟走了出来")
$link_self($node_near(28),"我来是想了解一下翡翠剑")
$step("甘瑟看见翡翠剑，似乎明白了什么，但他没有告诉你")
$link_this($node_near(28),$choice_near(25,1),"我来是想了解一下翡翠剑")
$step("是的，石台下镇压的是天使出现的原因，一直封闭着，没有人打开过（智力+2）","bruce")
$link_this($node_near(28),$choice_near(25,1),"我来是想了解一下翡翠剑","bruce")
$step("翡翠剑是在天使城铸造的。工匠是矮人族，也有精灵、魔法导师和炼金师的参与，它有一个特别的功能，就是感应黑暗力量。剑柄上原本镶嵌着一个被称作剑心的宝石，可以把生命力量转换为光明。甘瑟不知道剑心是怎么制造的，也不知道它为什么会消失","bruce")
$link_self($node_near(29),"那你知道什么")
$link_self($node_near(30),"那谁会知道（智力+）","bruce")
$step("我知道谁知道")
$link_this($node_near(30),$choice_near(28,2),"那谁会知道")
$step("毁掉剑心的人一定知道，除此之外，就是上一任的翡翠剑主人，阿宾","bruce")
$link_self($node_near(31),"他还活着？","bruce")
$link_self($node_near(32),"这不是废话吗（智力-）")
$step("他死在了龙骨山脉里，甘瑟做过很多探查，大概划出了一个范围","bruce")
$link_self($node(3,4))
$step("甘瑟生气了，你还听不听")
$link_this($node_near(31),$choice_near(30,1),"他还活着？")
$step("是的，它是专为与魔王作战锻造的")
$link_this($node_near(15),$choice_near(14,1),"上次见是什么时候")

@enduml
@startuml Ch3

!include head.puml!0

$step("瑟尔指的路下面是一片峭壁，隐约能看见一些可以搭手的藤蔓","None",3)
$link_self($node_near(5),"爬（驯服度+）","sinestro")
$link_self($node_near(30),"不爬")
$step("你穿越森林、攀过悬崖，最终爬上了山脊，步入白雪覆盖的领域，令你惊讶的是，山里有一道烟正在升起")
$link_self($node_near(31),"去看看")
$link_self($node_near(41),"专心赶路")
$step("这条路很好走，近乎坦途，沿路生长着灌木和苔藓，完全没有走错的可能，你一路前行，看到了路边的石碑，了解了大陆历史（知识+2）")
$link_self($node_near(43),"捡龙牙")
$step("你踏出传送阵，手中的翡翠剑就嗡鸣起来，带你走到了一个雪堆，看来这就是阿宾的坟。","bruce")
$link_self($node_near(50),"先祭奠一下")
$link_self($node_near(51),"直接动手挖坟")
$step("你屡次尝试，越爬越高，但在几十米后，上方突然出现了一道很大的凹痕，无法继续上攀，周围又开始下雨，你只好爬进凹痕暂避。雨越下越大，你估计这几天都爬不了山了，山壁滑不溜秋，无可奈何之下，你只好决定在凹痕深处暂时扎营。迷迷糊糊间，似乎看到一个人影站在雨幕之前。","sinestro")
$link_self($node_near(6),"谁在那儿")
$link_self($node_near(7),"摸剑")
$step("没人回答，那个人四下看了看，叹了口气：“这么大雨，没法爬山了”")
$link_self($node_near(8),"观察他")
$link_self($node_near(9),"伸手拍拍")
$step("你摸了个空，忽然想不起把剑放在了哪儿，只好朝那个人走去。")
$link_this($node_near(6),$choice_near(5,1))
$step("这个人穿得很整洁，连绑腿护腕都一丝不苟，斗篷上满是晶亮的雨水。他脱下斗篷放在一边，露出腰间的长剑，坐下开始进食，你在他面前晃了晃，他果然看不见你")
$link_self($node_near(10),"继续观察")
$link_self($node_near(11),"寻找其他线索")
$step("你伸手去拍他，手却从他身体里穿了过去，你吃了一惊，打量四周，发现似乎比你进来前要干净许多，你记得进来时凹痕口有一棵大树，可当你看去，那里却只有几棵杂草")
$link_this($node_near(8),$choice_near(6,1))
$step("那个人吃完饭，从领口里拽出一条工艺粗糙的链子，上面却有一颗很漂亮的菱形绿宝石吊坠，他摸着吊坠，似乎想起了谁，露出一个笑容。你从没见过那个吊坠，却觉得有些熟悉，正当你苦苦思索的时候，一道鸟鸣声忽然响起，一只漆黑的大鸟钻进了凹痕，它有三只赤红的眼睛，一只脚，两条长长的尾羽，你从没见过这样的东西，可那个人却不显得惊讶，立刻拔剑攻了上去。经过一番战斗，他成功战胜了怪鸟，但怪鸟的爪钩钩断了他颈上的链子，那颗吊坠带着链子，掉下了峭壁，他怔怔地在凹痕边站着，雨始终没有停")
$link_self($node_near(12),"别人的记忆","sinestro")
$link_self($node_near(13),"你的梦境")
$step("你之前的营地完全不见踪影，抓着爬上来的藤蔓也仿佛只是你的错觉，你发现，离那个人越远，眼前的景色就越模糊不清，看来，那个人才是一切的关键")
$link_this($node_near(10),$choice_near(8,1))
$step("谁的记忆","sinestro")
$link_self($node_near(14),"那个人","sinestro")
$link_self($node_near(15),"翡翠剑")
$step("哪只鸟你完全不认识，不可能梦得这么清晰")
$link_this($node_near(16),$choice_near(14,1),"深入凹痕")
$step("（驯化度+2）那个人和瑟尔长得截然不同，但如果不考虑样貌，只从逻辑推断，这条路是瑟尔给你指的，他一定走过；手里拿的不是翡翠剑，因此不是上一位勇者；所以，这段记忆的主人只可能是以前的瑟尔","sinestro")
$link_self($node_near(16),"深入凹痕")
$step("不，幻觉里没有翡翠剑")
$link_this($node_near(16),$choice_near(14,1),"深入凹痕")
$step("凹痕越来越窄，但始终有路可走，一些很窄的地方残留着非天然的痕迹，这条路应该以前有人走过，你点着火把一路深入，到了一处吊桥遗址，吊桥已经朽败，完全不能借力")
$link_self($node_near(17),"找藤蔓")
$link_self($node_end(5),"直接跳")
$new_end(5,"END 05 笼中之鸟")
$step("你从凹痕外弄来藤蔓，决定自造吊索，你抓起一块石头，忽然发现下面有一封信。信写给一个名为阿宾的人，告诉他自己遗失了阿琳送的吊坠，根据预言，自己这次讨伐黑暗力量，将再也回不来了，又详细描述了吊坠遗失时的情形，希望阿宾可以找到它。署名则是，瑟尔。你收起信，利用藤蔓制成的吊索，成功到达了另一端")
$link_self($node_near(18),"继续前进")
$step("沿着山路一直走，穿过一排藤蔓，炫目的光立刻淹没了你，你眼前是茫茫白雪，你已经到了龙骨雪山，翡翠剑忽然嗡鸣起来，你按照它指引的方向，绕过岩石、树木，来到了一处雪堆。翡翠剑哀鸣着，你猜，这是它上一任主人的埋骨之地","sinestro")
$link_self($node_near(19),"瑟尔？")
$link_self($node_near(20),"阿宾？")
$link_self($node_near(21),"阿琳？","sinestro")
$step("（智力-1）我怎么会是瑟尔，翡翠剑都不认得他。我的名字是阿宾")
$link_self($node_near(27),"我看到了他的信")
$link_self($node_near(22),"我以为他会在山上")
$step("年轻的勇士，你怎么会知道我的名字？根据信上的内容猜的，你不是死了吗？有时，死亡并不意味着终结。")
$link_self($node_near(22),"瑟尔是你什么人")
$link_self($node_near(21),"阿琳是谁")
$step("（好感度+1）她已久不在人世了，你怎么会知道她？","sinestro")
$link_self($node_near(27),"如实告知","sinestro")
$link_self($node_near(28),"含糊过去")
$step("你认得他？")
$link_self($node_near(23),"坦诚相告")
$link_self($node_near(24),"我还要脸")
$link_self($node_near(27),"捡到了他的信")
$step("他曾经是我最好的朋友，也是前去讨伐魔王的勇者，预言上说，如果他丢失了那枚吊坠，他就会被黑暗吞没。那我睡的是谁？或许预言错了，或许被黑暗吞没，不只有死亡一种可能","sinestro")
$link_self($node_near(25),"他是我的敌人？")
$link_self($node_near(26),"（驯化度=7）他还可以被拯救吗","sinestro")
$step("我不明白他要对你做什么，但是，当心")
$link_self($node_near(23),"怎么说？")
$step("没错。在战斗时，你最好忘记你与他认识，因为他是不会在意的，还有一件事")
$link_this($node_near(29),$choice_near(28,1),"请说")
$step("（好感度+2）我不知道，我只是个死人。剑在你手中，路在你脚下，未来世界什么样子，都在你的一念之间，还有一件事","sinestro")
$link_this($node_near(29),$choice_near(28,1),"请说")
$step("原来如此，原来他还留了一封信。我是阿宾，也是翡翠剑的第一任主人。阿琳……是我妹妹。我那个年代，黑暗力量侵袭，她的未婚夫瑟尔，尽管有着不祥的预言，但还是作为勇者出发了。他没有回来，我们在他经过的峭壁下捡到了那枚吊坠。我决定继续他未竟的事业，因为黑暗在变强，获得了很多支持，也就有了翡翠剑，阿琳为了确保胜利，用自己的生命和灵魂，为我铸就了翡翠剑的剑心，可，我却辜负了她，不仅自己战败身死，连剑心也毁了","sinestro")
$link_self($node_near(23),"信上的瑟尔又是谁？","sinestro")
$step("你不想说，我不强求。我是阿宾，翡翠剑的第一任主人。你出现在这里，是为了去讨伐魔王吧。抱歉，我战败了，给不了你什么帮助，只有一件事能告诉你")
$link_self($node_near(29),"请说")
$step("翡翠剑的本质是勇气，持剑的时候，永远不要忘记这一点")
$link_self($node(4,1),"告辞离开")
$step("你担心这条路可能已经没法走了，沿着山脉前行，走上了原定的翻山之路")
$link_self($node_near(2),"出发")
$step("你朝烟雾升起的方向走去，在一处山坳，发现了一座林中小屋，一个人恰好从小屋里走出来，竟然是卡萝，她在你之后出发，追查一支很奇怪的箭，与精灵族相识，在这里学习炼金术（知识+3）")
$link_self($node_near(32),"为什么选这儿")
$link_self($node_near(33),"这里安全吗")
$link_self($node_near(34),"可以参观吗")
$step("交通便利")
$link_this($node_near(31))
$link_this($node_near(49),$choice_near(31,4),"有什么能帮忙的")
$step("很安全，卡萝比你想得厉害")
$link_this($node_near(31))
$link_this($node_near(49),$choice_near(31,4),"有什么能帮忙的")
$step("获得通讯水晶")
$link_this($node_near(31))
$link_this($node_near(49),$choice_near(31,4),"有什么能帮忙的")
$step("处理材料")
$link_self($node_near(36),"处理羽毛")
$link_self($node_near(36),"处理金属")
$link_self($node_near(36),"处理骨头")
$link_self($node_near(37),"附魔翅膀")
$link_self($node_near(37),"附魔身体")
$link_self($node_near(38),"成功")
$link_self($node_near(39),"失败")
$step("怎么处理")
$link_self($node_near(35),"（羽毛）清洁")
$link_self($node_near(35),"（金属）熔化")
$link_self($node_near(35),"（骨头）粉碎")
$step("什么属性")
$link_self($node_near(35),"（翅膀）风属性")
$link_self($node_near(35),"（身体）水属性")
$step("一滴血（获得坐骑，智力+3）")
$link_self($node_near(40),"去黑暗领域怎么走")
$step("卡萝嫌弃")
$link_this($node_near(40),$choice_near(38,1),"去黑暗领域怎么走")
$step("先去哥谭")
$link_self($node(5,1),"第五章 孤城")
$step("积雪不深，你行走时发现雪下面有东西")
$link_self($node_near(42),"捡")
$link_self($node_near(43),"不捡")
$step("一根白色的锥形棍子")
$link_self($node_near(43))
$step("你发现一个奇怪的雪洞")
$link_self($node_near(44),"进")
$link_self($node_near(45),"不进")
$step("有野果，吃得很饱")
$link_self($node_near(45))
$step("你走在路上，忽然被什么绊了一下，定睛一看，雪地里有着一段雪白的骨头，雪地起伏，似乎是一具很大的尸骨，你沿着尸骨前进，到了一处突出的山头，地势陡峭")
$link_self($node_near(46),"（吃饱了且有龙牙）")
$link_self($node_near(47),"（吃饱了但没龙牙）")
$link_self($node_near(48),"（没吃饱）")
$step("你爬上了山头，脚下忽然开始震动，好一阵子才平息下来，你发现自己站在雪白的尸骨上，脚下，似乎是一颗头颅，脑袋里，少了一颗牙，你把白色锥形棍装进孔洞里，尸骨闪了闪，眼睛的空洞里有绚烂的光放出，你看到了三百年前的大战画面，一只冰蓝色的巨龙用尽最后的力量立起一条雄伟的山脉，隔绝了大陆两侧，自己力竭倒地，三百年的时光倏忽而过，你仿佛看到黑暗那边有一座城（智力+1）")
$link_self($node(5,1),"第五章 孤城")
$link_self($node(4,2),"第四章 远方")
$step("你借助好视野，画了一幅地图，向被黑暗笼罩的地方出发")
$link_this($node(4,2),$choice_near(46,2),"第四章 远方")
$step("你想爬，但却没有足够的体力，只好放弃了")
$link_self($node(4,1))
$step("新作品")
$link_self($node_near(35),"开始")
$step("雪堆竟然回应了，你吃了一惊，他的灵魂没有消散，向你讲述了他和魔王的故事，但死后的事他不知道，因此也不知道翡翠剑后来怎样，或许他的尸体会记得，于是你在他的同意下刨开雪堆（知识+）")
$link_this($node_near(52),$choice_near(4,3),"回溯")
$step("你刨开雪堆，仿佛听到了一声久远之前的叹息")
$link_this($node_near(52),$choice_near(4,3),"回溯")
$step("你对着尸骨进行回溯")
$link_self($node_near(53),"头骨")
$link_self($node_near(54),"胸骨")
$link_self($node_near(55),"臂骨")
$link_self($node_near(56),"脊椎")
$link_self($node_near(57),"（可选）破烂披风")
$step("剑心的铸造")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("决战，阿宾被瑟尔掏出心脏")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("阿宾和瑟尔练剑，瑟尔的弱点")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("阿宾记忆里的小镇")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("天使城的传说（知识+）","bruce")
$link_this($node_near(52))
$link_this($node_near(58),$choice_near(52,6))
$step("下一步计划","bruce")
$link_self($node_near(59),"讨伐魔王")
$link_self($node_near(60),"哥谭（不认识布鲁斯）")
$link_self($node_near(61),"哥谭（认识布鲁斯）","bruce")
$step("前方被山挡住了，从哪边绕")
$link_self($node(4,1),"左")
$link_self($node_near(41),"右")
$step("你从山顶出发，路上不慎滑了一跤，在雪地里滑出去很远，最后撞上树，灰头土脸地爬起来，已经在一座山谷里了，你发现附近有一条被踩出来的小路，你决定去碰碰运气")
$link_self($node_near(62),"向左")
$link_self($node_near(63),"向右")
$step("你忽然想起，布鲁斯曾说过他是哥谭人，想起布鲁斯，你忽然对他和哥谭感到万分好奇，晚上你找了个避风的山洞露营，外面忽然刮起风雪，翡翠剑旁的雪融化，留下一个菱形的坑。","bruce")
$link_self($node_near(68),"出去看看","bruce")
$link_self($node_near(69),"好好休息")
$step("你走到了一处路口，面前有两条岔路")
$link_self($node_near(64),"向左")
$link_self($node_near(65),"向右")
$link_self($node_near(63),"（第一次来）回头")
$step("你在路边看到了一块大石，上面刻了去哥谭的路，三岔路口右转，溪边向上游前进，森林前的大路朝山上走")
$link_self($node_near(62))
$step("你迷路在了山林里，快要饿死的时候，遇到了猎人，对方把你带到了哥谭")
$link_self($node(5,1))
$step("走到了溪边")
$link_self($node_near(66),"向上游")
$link_self($node_near(64),"向下游")
$link_self($node_near(64),"涉水走对岸的路")
$step("走到了森林边，小溪是从森林里流出来的，森林前有一条宽敞的路，左侧通向一片平原，右侧通向山上")
$link_self($node_near(64),"进森林")
$link_self($node_near(67),"左转")
$link_self($node(5,1),"右转（智力+2）")
$step("你走到了一座冰湖，饱览了冰天雪地的奇异风景")
$link_self($node(5,1))
$step("你在风雪中仿佛看到一个漆黑的人影，走近了却又见不到人，你无功而返，在山洞前看到了几个脚印，你小心地持剑走了进去，却发现这不是你的山洞。你拐过一个弯，对上了一双深蓝的眼睛","bruce")
$link_self($node_near(70),"（智力=3）布鲁斯？（好感度+2）","bruce")
$link_self($node_near(71),"防御")
$link_self($node_near(72),"进攻（好感度-3）")
$step("你在风雪中度过一夜")
$link_this($node_near(60),$choice_near(58,2))
$step("哈尔？你怎么跑到这儿来的。你告诉他自己准备去哥谭，刚刚翡翠剑有反应，你担心是黑暗力量作祟","bruce")
$link_this($node_near(73),$choice_near(68,4))
$step("对方并没有进攻，你与他对视片刻：“布鲁斯？”")
$link_this($node_near(73),$choice_near(68,4))
$step("对方和你过了几招，你把他逼到墙边，听到对方念了几个你听不懂的词，你忽然动弹不得，听到他说：“你有毛病吗，勇者？”")
$link_this($node_near(73),$choice_near(68,4))
$step("一只鹰魔跨越边界上了龙骨雪山，布鲁斯来追杀它","bruce")
$link_self($node_near(74),"鹰魔是什么","bruce")
$link_self($node_near(75),"需要我帮忙吗")
$step("（知识+1）","bruce")
$link_this($node_near(75),$choice_near(73,2),"","bruce")
$step("布鲁斯静静地扫视了你一下，说不用，等风雪停了他自己可以，你待在山洞里就行","bruce")
$link_self($node_near(76),"坚持帮忙")
$link_self($node_near(77),"不再插手")
$link_self($node_near(77),"假意同意","bruce")
$step("（好感度-）布鲁斯表示你要找死他不管")
$link_this($node_near(78),$choice_near(75,4),"等雪停")
$step("布鲁斯冷淡地朝你点点头","bruce")
$link_this($node_near(78),$choice_near(75,4),"等雪停","bruce")
$step("风雪停下时天还没亮，布鲁斯从口袋里掏出一个吊坠戴在脖子上，一颗拇指大的珍珠在他的魔法下发出明亮的光，他看着你的眼神，也给了你一个，转身走出了山洞","bruce")
$link_self($node_near(79),"（假意答应）稍后跟上","bruce")
$link_self($node_near(80),"（坚持）跟上")
$link_self($node_near(81),"原地等候")
$step("你跟出去的时候布鲁斯已经在和鹰魔交战了，他的剑术很好，但鹰魔的速度实在太快，因此他也多少有些应付不过来，你冲上去帮他，他不怎么领情，并肩作战，成功收拾了鹰魔（好感度+3）","bruce")
$link_this($node(5,1),$choice_near(78,4))
$step("你跟在布鲁斯身后，没走出多远就被鹰魔突袭了。你从没应付过这种局面，险象环生，布鲁斯非常生气，最后你们杀掉了鹰魔，你也挂了彩，没受伤的他把你狠狠训了一顿")
$link_this($node(5,1),$choice_near(78,4))
$step("过了几个小时，布鲁斯带伤归来，他有一道很大的伤口，并不深，但还是流了不少血，你给他包扎，他虽然拒绝，但无力反抗。最后他很费劲地说了谢谢（好感+）")
$link_this($node(5,1),$choice_near(78,4),"","bruce")

@enduml
@startuml Ch4

!include head.puml!0

$step("你在雪山上绕了挺久，终于找到路下山。（hp+80）","None",4)
$link_self($node_near(3),"下山")
$step("你沿着地图前进，没花多少时间（hp+100）")
$link_this($node_near(3),$choice_near(1,1),"下山")
$step("你接近山脚才发现，与黑暗领域相连的龙骨雪山大部分是冰雪覆盖的悬崖绝壁，两边连通的路屈指可数。你在这条路边遇到了一个酒馆，走进去发现几乎坐满了，只有几桌可以加人")
$link_self($node_near(4),"衣着肮脏的强壮武士")
$link_self($node_near(5),"职业均衡的守卫小队")
$link_self($node_near(6),"带着兜帽的孤身法师")
$step("邀请你同行")
$link_self($node_end(6),"答应")
$new_end(6,"END06 自不量力")
$link_self($node_near(7),"拒绝")
$step("了解了很多知识（知识+5）")
$link_self($node_near(7),"出发")
$step("你在他对面坐下，要了一点热食，突然发现对面的人非常熟悉，你叫出他的名字，立刻引来了攻击，你们花了好大力气逃掉，躲在巴里的藏身处。他把你抱怨一顿，你反问他那么强的魔法是哪儿来的")
$link_self($node_near(8),"你到底是什么人")
$link_self($node_near(9),"你在小镇干什么")
$link_self($node_near(10),"你怎么会在这儿")
$step("孤身上路\n战斗关卡")
$link_self($node_end(7),"胜利（赛叔好感度<5）")
$new_end(7,"END07 无心之过")
$link_self($node_near(13),"胜利（赛叔好感度>=5）","sinestro")
$link_self($node_end(6),"失败")
$step("雷电系大魔法师，光明骑士团的一员，如果你需要的话，还是你的队友")
$link_this($node_near(6))
$link_this($node_near(11),$choice_near(6,4),"我可以相信你吗")
$step("观察长老团，他们有些不愿意让人知道的秘密，他怀疑和天使城的谜团有关")
$link_this($node_near(6))
$link_this($node_near(11),$choice_near(6,4),"我可以相信你吗")
$step("说来话长，但现在你们的目标是一致的，都要深入黑暗领域")
$link_this($node_near(6))
$link_this($node_near(11),$choice_near(6,4),"我可以相信你吗")
$step("巴里表情一僵，你哈哈大笑，他才意识到你在耍他。你们休息一夜就上路了。从龙骨雪山出去先是战区，战区非常混乱，常常会遇到魔的袭击，守卫小队会定期进来巡逻，防止战区的魔太多，侵扰龙骨雪山")
$link_self($node_near(12),"胜利")
$link_self($node_end(6),"失败")
$step("你们在战区一路走一路杀，抵达了黑暗领域真正的边境，你们被巡视的魔发现了，陷入苦战，情急之下，巴里使用了一个传送魔法，你们到了哥谭一座瞭望塔顶上")
$link_self($node(5,4))
$step("你穿过战区，潜入黑暗领域，紧张地躲避着魔的巡逻，你肩头的牙印忽然发烫，瑟尔出现在你面前：“还记得我吗？哈尔？”","sinestro")
$link_self($node_near(14),"你哪位")
$link_self($node_near(15),"有什么事")
$link_self($node_near(16),"你又要我上你吗","sinestro")
$step("（好感度-）")
$link_self($node_near(17),"这里不安全")
$link_self($node_near(18),"脱衣服","sinestro")
$link_self($node_near(19),"你真奇怪")
$step("")
$link_this($node_near(14))
$step("（驯化度+）","sinestro")
$link_this($node_near(14))
$step("（驯化度-）")
$link_this($node_near(20),$choice_near(14,4))
$step("（好感度+）","sinestro")
$link_this($node_near(20),$choice_near(14,4))
$step("")
$link_this($node_near(20),$choice_near(14,4))
$step("你又和瑟尔搞了一次，这次留意到了更多的细节，你忍不住开始思索他究竟是什么人，可瑟尔的话声打断了你的思绪：“你还是要去杀了魔王吗”","sinestro")
$link_self($node_near(29),"没错","sinestro")
$link_self($node_near(22),"我在考虑")
$step("瑟尔表示他也要去魔王宫殿，你们可以同路","sinestro")
$link_self($node_near(23),"答应","sinestro")
$link_self($node_near(24),"拒绝")
$step("黑暗生物有着自己的意识，就意味着可以交流，或许双方可以共存（驯化度归零）")
$link_self($node_near(21))
$step("你们一同前往魔王宫殿","sinestro")
$link_self($node_near(25),"（同路）","sinestro")
$step("（好感度归零）瑟尔祝你好运")
$link_this($node_near(26),$choice_near(23,2),"（独自）")
$step("你发现瑟尔身上有许多疑点，比起人，更像是个魔，信上的预言萦绕在你心头，你总觉得背后有着一个会令你大吃一惊的秘密。最后，你们到了魔王的宫殿外，宏伟的建筑近在咫尺，瑟尔停下了脚步","sinestro")
$link_self($node_near(27),"（驯化度=8）打起来之前，不请我进你家看看吗？","sinestro")
$link_self($node_near(28),"（好感<8）拔剑")
$link_self($node_end(10),"怎么了？")
$new_end(10,"END10 翡翠暮光")
$step("你独自抵达了魔王的宫殿，瑟尔就站在那里等你")
$link_this($node_near(25))
$step("瑟尔拒绝，你们打了起来，最终你获胜，笑着问他现在可你带你参观了吗","sinestro")
$link_self($node_end(11),"（好感度=8）再给他一次机会","sinestro")
$new_end(11,"END11 家养猫咪")
$link_self($node_end(12))
$new_end(12,"END12 晴空万里")
$step("你战败了")
$link_self($node_end(8),"（驯化度满）")
$new_end(8,"END08 不见天日")
$link_self($node_end(9),"（驯化度<8）")
$new_end(9,"END09 命丧他乡")
$step("我的想法还没变","sinestro")
$link_this($node_near(21),$choice_near(22,1),"sinestro")

@enduml
@startuml Ch5

!include head.puml!0

$step("初见哥谭","bruce",5)
$link_self($node_near(26),"（自己出现）")
$link_self($node_near(2),"（卡罗介绍）")
$link_self($node_near(27),"和布鲁斯一起","bruce")
$step("你走进城门，通讯水晶开始发光，一个人影浮现在其中，让你去哥谭的中央广场和他见面")
$link_self($node_near(5),"（认识布鲁斯）")
$link_self($node_near(6),"（认识布鲁斯但不知道名字）")
$link_self($node_near(7),"（不认识布鲁斯）")
$step("布鲁斯带你去了他家，承诺解答你的疑问","bruce")
$link_self($node_near(13),"你到底是什么人？","bruce")
$step("你们从瞭望塔上下来，巴里带你去了布鲁斯家，介绍你们认识")
$link_self($node_near(9),"认识布鲁斯")
$link_self($node_near(10),"不认识布鲁斯")
$step("")
$link_this($node_near(8),$choice_near(2,4))
$step("")
$link_this($node_near(8),$choice_near(2,4))
$step("")
$link_this($node_near(8),$choice_near(2,4))
$step("布鲁斯请你去他家坐坐，他有一些事情想告诉你")
$link_self($node_near(3),"走吧")
$step("")
$link_this($node_near(12),$choice_near(4,3))
$step("")
$link_self($node_near(11),"认识但不知道名字")
$step("")
$link_this($node_near(12),$choice_near(4,3))
$step("布鲁斯对你们的经历有一点惊讶，但他挺高兴你们跑来了，省了他等人的时间")
$link_this($node_near(13),$choice_near(3,1))
$step("龙语者","bruce")
$link_this($node_near(14),$choice_near(3,2),"找我来干什么？","bruce")
$step("我想帮你","bruce")
$link_this($node_near(15),$choice_near(3,3),"都什么乱七八糟的","bruce")
$step("天色很晚了，布鲁斯让你好好休息，明天再说，不过你想在这座城堡里逛逛","bruce")
!$tmp=$node($node_now(),1)
$link_self($tmp)
$new($tmp,"主建筑")
$link($tmp,$node_near(16),$node($tmp,1),"一楼（客厅）")
$link($tmp,$node_near(18),$node($tmp,2),"二楼（客房）")
$link($tmp,$node_near(19),$node($tmp,3),"三楼（主卧）")
!$tmp=$node($node_now(),2)
$link_self($tmp)
$new($tmp,"东塔楼")
$link($tmp,$node_near(20),$node($tmp,1),"一层（厨房）")
$link($tmp,$node_near(21),$node($tmp,2),"二层（天台）")
!$tmp=$node($node_now(),3)
$link_self($tmp)
$new($tmp,"西塔楼")
$link($tmp,$node_near(22),$node($tmp,1),"一层（书房）")
$link($tmp,$node_near(23),$node($tmp,2),"二层（收藏）")
$link_self($node_near(24),"地下室")
$link_self($node_near(25),"地下室（不是第一次去）")
$step("没人了")
$link_self($node_near(17),"再逛逛")
$step("城堡")
$link_this($node_near(15))
$step("是否休息")
$link_self($node_near(28),"现在休息")
$link_this($node_near(17))
$step("不让进")
$link_this($node_near(17))
$step("饱餐一顿")
$link_this($node_near(17))
$step("看星星（知识+1）","bruce")
$link_this($node_near(17))
$step("哥谭藏书（知识+2）","bruce")
$link_this($node_near(17))
$step("龙语者与龙（智力+1）","bruce")
$link_this($node_near(17))
$step("龙蛋（知识+3）","bruce")
$link_this($node_near(17))
$step("")
$link_this($node_near(17))
$step("在城外，一个人拦住了你，交给你一块通讯水晶")
$link_this($node_near(2),$choice_near(1,2))
$step("布鲁斯给你准备了通讯水晶","bruce")
$link_this($node_near(3),$choice_near(8,1),None,"bruce")
$step("布鲁斯讲了讲你的特训，对其他计划却只字不提","bruce")
$link_self($node_near(29),"（智力>2）要他解释（布鲁斯好感>8）","bruce")
$link_self($node_near(30),"（智力>2）要他解释")
$link_self($node_near(31),"半信半疑")
$step("详细的解释","bruce")
$link_self($node_near(32),"帮忙找出卧底","bruce")
$link_self($node_end(13),"让布鲁斯去操心")
$new_end(13,"END 13 匹夫之勇")
$step("简单的解释")
$link_this($node_near(32),$choice_near(29,1),"帮忙找出卧底")
$link_this($node_end(13),$choice_near(29,1),"让布鲁斯去操心")
$step("布鲁斯搪塞过去，只说是利用城里隐藏的卧底把魔王引过来")
$link_self($node_end(13),"不再管了")
$step("布鲁斯为你简单介绍了当前情况，你有三个地方需要调查，如果你需要什么东西，城堡里的随便拿","bruce")
$link_self($node_near(33),"北端城堡")
$link_self($node_near(40),"中央广场在白天")
$link_self($node_near(41),"中央广场在晚上")
$link_self($node_near(44),"城东枯井","bruce")
$link_self($node_near(46),"城南旧屋（白天）")
$link_self($node_near(47),"城南旧屋（晚上）")
$link_self($node_near(51),"包括龙蛋吗？（好感度+4）","bruce")
$step("")
$link_self($node_near(34),"拿提灯","bruce")
$link_self($node_near(35),"拿生命晶石","bruce")
$link_self($node_near(36),"（发现胳膊）找布鲁斯","bruce")
$step("","bruce")
$link_this($node_near(32))
$step("","bruce")
$link_this($node_near(32))
$step("城里没有人有这种新伤，布鲁斯观察了一下，认为应该是魔族的手臂，他把鲜血滴进一瓶魔药，魔药由白变黑又变红，这是困魔药水，用它就可以抓住魔","bruce")
$link_this($node_near(32))
$step("")
$link_self($node_near(38),"（没有胳膊）")
$link_self($node_near(39),"（有胳膊）")
$step("不治身亡")
$link_self($node_end(13))
$step("布鲁斯费了很大的力气，把它救活了")
$link_this($node_near(53),$choice_near(52,1))
$step("（白天）中央广场人来人往，你在这里一直晃到晚上，一无所获")
$link_this($node_near(32))
$step("（晚上）你在中央广场的角落里观察，一道黑影掠过")
$link_self($node_near(42),"（有生命晶石）")
$link_self($node_near(43),"（没有）")
$step("翡翠剑从你手中飞出，把黑影钉在了地上，黑影立刻死亡，你只好把尸体拖回去给布鲁斯，布鲁斯很生气")
$link_this($node_end(13),$choice_near(38,1))
$step("你追到城东，黑影把你甩掉了，你无功而返")
$link_this($node_end(13),$choice_near(38,1))
$step("你来到枯井，翡翠剑对黑暗力量有了反应","bruce")
$link_self($node_near(45),"（有提灯）爬下去")
$link_self($node_end(14),"（无提灯）跳下去")
$new_end(14,"END 14 猎魔人")
$link_self($node_near(63),"先回城堡")
$step("你慢慢下到井底，发现了一根鲜血淋漓的胳膊，你没直接碰，用披风裹了起来","bruce")
$link_this($node_near(32))
$step("（白天）你四下问了问，这座屋子已经荒废很久了，以前……")
$link_this($node_near(32))
$step("（晚上）","bruce")
$link_self($node_near(48),"（有困魔药水和生命晶石）","bruce")
$link_self($node_near(49),"（有生命晶石）")
$link_self($node_near(50),"（没有药水）")
$link_self($node_near(64),"（有药水，没有晶石）")
$step("你把药水洒在屋子角落里，轻而易举地抓住了卧底","bruce")
$link_self($node_near(52),"带回去给布鲁斯")
$step("你与魔族缠斗一番，虽然赢了，但它也只剩下了半口气")
$link_self($node_near(37),"带回去")
$step("你没能抓到卧底")
$link_this($node_end(13),$choice_near(38,1))
$step("搬得动你就拿","bruce")
$link_this($node_near(32))
$step("布鲁斯感谢了你","bruce")
$link_self($node_near(53),"接下来怎么办？")
$step("布鲁斯让你养精蓄锐，好好练剑，他会在决战时间定下来后通知你。你专心练剑，布鲁斯花了很多时间来当你的陪练。一个月后，他告诉你三天之后就是决战的日子了。","bruce")
$link_self($node_near(54),"（通过卡萝的考验）")
$link_self($node_near(55),"当天晚上","bruce")
$step("她给你送来了一匹飞马")
$link_this($node_near(55),$choice_near(53,2))
$step("布鲁斯问你需不需要壮行宴会，被你谢绝了，你只想醉一场。你们翻箱倒柜，找出了几瓶满是灰尘的酒水，喝到最后也只是半醉，回房睡觉，到了二楼","bruce")
$link_self($node_near(56),"回房间","bruce")
$link_self($node_near(57),"上三楼（带回了健康的魔族）")
$link_self($node_near(58),"上三楼（没带回健康的魔族）")
$step("你睡到日上三竿，觉得身上积蓄的疲惫一扫而空","bruce")
$link_this($node(6,1),$choice_near(59,1))
$step("布鲁斯看着你，轻声道，你需要好好休息，你回答：我知道")
$link_this($node_near(56),$choice_near(55,1),"回房睡觉")
$link_this($node_near(58),$choice_near(55,3),"跟着他走")
$step("你跟着布鲁斯回了卧室，共度了甜蜜而炙热的一夜，醒来时，布鲁斯已经不在枕边了")
$link_self($node_near(59),"东塔楼")
$link_self($node_near(59),"西塔楼")
$link_self($node_near(59),"城堡一楼")
$link_self($node_near(60),"（之前见过龙蛋）地下室")
$link_self($node_near(61),"（没见过龙蛋）地下室")
$step("你没找到布鲁斯")
$link_self($node(6,1),"备战，两天后")
$step("你走到龙蛋边，忍不住想伸手摸一摸")
$link_self($node_near(62),"摸一下")
$step("你来到地下室，布鲁斯向你介绍了巨龙")
$link_this($node_near(62),$choice_near(60,1),"摸一下")
$step("你把手放到布鲁斯手上，他立刻扭过头，可能是想呵斥你两句，但一道蓝色波纹撞上他的手心，他最终什么都没有说。你说道，你说很快就能孵出来；布鲁斯点点头，是的，于是你笑了笑，这么说来，我可以先见到你再回OA。然后你看向布鲁斯：在哥谭的太阳下。")
$link_this($node(6,1),$choice_near(59,1))
$step("")
$link_this($node_near(33))
$step("你把药水涂在身上，偷袭了魔族，不慎重伤了它")
$link_this($node_near(37),$choice_near(49,1))
$step("决战日","None",6)
$link_self($node_near(2))
$step("布鲁斯")
$link_self($node_near(3))
$step("哥谭百姓")
$link_self($node_near(4))
$step("光明骑士团")
$link_self($node_near(5))
$step("魔王\n战斗关卡")
$link_self($node_end(16),"战斗胜利（睡了布鲁斯）")
$new_end(16,"END16 旭日东升")
$link_self($node_end(17),"战斗胜利（布鲁斯好感度=20）")
$new_end(17,"END17 无尽冒险")
$link_self($node_end(18),"战斗胜利")
$new_end(18,"END18 翡翠长明")
$link_self($node_end(15),"战斗失败")
$new_end(15,"END15 万灵恸哭")
@enduml
@startuml Ch7

!include head.puml!0
$step("你在天使城里闲逛，忽然听到了竖琴声，你循声走进酒馆，吟游诗人唱着一个故事，魔王隐瞒身份与勇者相遇，二人成为了朋友。二人一路同行，勇者明知那是敌人，却爱上了魔王；魔王也爱上了勇者",None,7)
$link_self($node_end(19),"打断他")
$new_end(19,"END 19 视差未来")
$link_self($node_near(2),"继续听")
$step("他们一直走到魔王的宫殿，图穷匕见，魔王没有抵抗，死在了勇者剑下。心中矛盾的勇者被魔王的力量侵蚀，成为了新的魔王")
$link_this($node_end(19),$choice_near(1,1))
$link_self($node_near(3),"继续听")
$step("新的魔王拥有双倍的力量，摧枯拉朽般战胜了人类，黑暗笼罩了全大陆。故事告一段落，吟游诗人看向你，想问问勇者有什么看法")
$link_self($node_end(19),"瞎几把扯")
$link_self($node_near(5),"不就是个悲剧")
$link_self($node_near(4),"你跑调了")
$step("谁问你这个了！")
$link_this($node_near(5))
$step("你找了个清净地方，和凯尔仔细分析了“魔王隐瞒身份遇到勇者”的可能性，结论是其概率实在低到不值得认真对待。你去神殿问翡翠剑的事，发现天使雕像成了凯尔的模样")
$link_self($node_near(6),"（知识>5）那个故事真的发生了")
$link_self($node_near(8),"（认识布鲁斯但知识不足）你是什么人")
$link_self($node_near(9),"你是天使？")
$step("凯尔带你走进神殿，神殿中央是一个龟裂的黑色石台，那是穿越时间留下的痕迹。凯尔来自你成为魔王的未来，但你却并不认识魔王，你唯一认识的是布鲁斯，出于保险起见，你决定和凯尔一起上路")
$link_self($node_end(20),"讨伐魔王")
$new_end(20,"END 20 未曾设想")
$link_self($node_near(7),"先找找布鲁斯是谁")
$step("你们查到了哥谭的信息，确定布鲁斯并不是魔王。你和凯尔在一起，对改变未来充满信心，你们走出神殿，一只老鼠跑过，凯尔拔出剑去打，半天都没打到。你把老鼠斩于剑下，凯尔尴尬地解释，他并不懂得战斗")
$link_this($node_end(21),$choice_near(8,1))
$new_end(21,"END 21 破晓曙光")
$step("凯尔是来阻止你的，你不置可否，和凯尔打了一架，轻松取胜，凯尔甚至没练过剑的样子")
$link_self($node_end(21),"你这样，来阻止我？")
$step("不，凯尔只是个来自你成为魔王的未来的普通人，路过神殿门口，被甘瑟抓了壮丁")
$link_this($node_end(21),$choice_near(8,1))
@enduml