@startuml Ch5

!include head.puml!0

$step("初见哥谭","bruce",5)
$link_self($node_near(26),"（自己出现）")
$link_self($node_near(2),"（卡罗介绍）")
$link_self($node_near(27),"和布鲁斯一起","bruce")
$step("你走进城门，通讯水晶开始发光，一个人影浮现在其中，让你去哥谭的中央广场和他见面")
$link_self($node_near(5),"（认识布鲁斯）")
$link_self($node_near(6),"（认识布鲁斯但不知道名字）")
$link_self($node_near(7),"（不认识布鲁斯）")
$step("布鲁斯带你去了他家，承诺解答你的疑问","bruce")
$link_self($node_near(13),"你到底是什么人？","bruce")
$step("你们从瞭望塔上下来，巴里带你去了布鲁斯家，介绍你们认识")
$link_self($node_near(9),"认识布鲁斯")
$link_self($node_near(10),"不认识布鲁斯")
$step("")
$link_this($node_near(8),$choice_near(2,4))
$step("")
$link_this($node_near(8),$choice_near(2,4))
$step("")
$link_this($node_near(8),$choice_near(2,4))
$step("布鲁斯请你去他家坐坐，他有一些事情想告诉你")
$link_self($node_near(3),"走吧")
$step("")
$link_this($node_near(12),$choice_near(4,3))
$step("")
$link_self($node_near(11),"认识但不知道名字")
$step("")
$link_this($node_near(12),$choice_near(4,3))
$step("布鲁斯对你们的经历有一点惊讶，但他挺高兴你们跑来了，省了他等人的时间")
$link_this($node_near(13),$choice_near(3,1))
$step("龙语者","bruce")
$link_this($node_near(14),$choice_near(3,2),"找我来干什么？","bruce")
$step("我想帮你","bruce")
$link_this($node_near(15),$choice_near(3,3),"都什么乱七八糟的","bruce")
$step("天色很晚了，布鲁斯让你好好休息，明天再说，不过你想在这座城堡里逛逛","bruce")
!$tmp=$node($node_now(),1)
$link_self($tmp)
$new($tmp,"主建筑")
$link($tmp,$node_near(16),$node($tmp,1),"一楼（客厅）")
$link($tmp,$node_near(18),$node($tmp,2),"二楼（客房）")
$link($tmp,$node_near(19),$node($tmp,3),"三楼（主卧）")
!$tmp=$node($node_now(),2)
$link_self($tmp)
$new($tmp,"东塔楼")
$link($tmp,$node_near(20),$node($tmp,1),"一层（厨房）")
$link($tmp,$node_near(21),$node($tmp,2),"二层（天台）")
!$tmp=$node($node_now(),3)
$link_self($tmp)
$new($tmp,"西塔楼")
$link($tmp,$node_near(22),$node($tmp,1),"一层（书房）")
$link($tmp,$node_near(23),$node($tmp,2),"二层（收藏）")
$link_self($node_near(24),"地下室")
$link_self($node_near(25),"地下室（不是第一次去）")
$step("没人了")
$link_self($node_near(17),"再逛逛")
$step("城堡")
$link_this($node_near(15))
$step("是否休息")
$link_self($node_near(28),"现在休息")
$link_this($node_near(17))
$step("不让进")
$link_this($node_near(17))
$step("饱餐一顿")
$link_this($node_near(17))
$step("看星星（知识+1）","bruce")
$link_this($node_near(17))
$step("哥谭藏书（知识+2）","bruce")
$link_this($node_near(17))
$step("龙语者与龙（智力+1）","bruce")
$link_this($node_near(17))
$step("龙蛋（知识+3）","bruce")
$link_this($node_near(17))
$step("")
$link_this($node_near(17))
$step("在城外，一个人拦住了你，交给你一块通讯水晶")
$link_this($node_near(2),$choice_near(1,2))
$step("布鲁斯给你准备了通讯水晶","bruce")
$link_this($node_near(3),$choice_near(8,1),None,"bruce")
$step("布鲁斯讲了讲你的特训，对其他计划却只字不提","bruce")
$link_self($node_near(29),"（智力>2）要他解释（布鲁斯好感>8）","bruce")
$link_self($node_near(30),"（智力>2）要他解释")
$link_self($node_near(31),"半信半疑")
$step("详细的解释","bruce")
$link_self($node_near(32),"帮忙找出卧底","bruce")
$link_self($node_end(13),"让布鲁斯去操心")
$new_end(13,"END 13 匹夫之勇")
$step("简单的解释")
$link_this($node_near(32),$choice_near(29,1),"帮忙找出卧底")
$link_this($node_end(13),$choice_near(29,1),"让布鲁斯去操心")
$step("布鲁斯搪塞过去，只说是利用城里隐藏的卧底把魔王引过来")
$link_self($node_end(13),"不再管了")
$step("布鲁斯为你简单介绍了当前情况，你有三个地方需要调查，如果你需要什么东西，城堡里的随便拿","bruce")
$link_self($node_near(33),"北端城堡")
$link_self($node_near(40),"中央广场在白天")
$link_self($node_near(41),"中央广场在晚上")
$link_self($node_near(44),"城东枯井","bruce")
$link_self($node_near(46),"城南旧屋（白天）")
$link_self($node_near(47),"城南旧屋（晚上）")
$link_self($node_near(51),"包括龙蛋吗？（好感度+4）","bruce")
$step("")
$link_self($node_near(34),"拿提灯","bruce")
$link_self($node_near(35),"拿生命晶石","bruce")
$link_self($node_near(36),"（发现胳膊）找布鲁斯","bruce")
$step("","bruce")
$link_this($node_near(32))
$step("","bruce")
$link_this($node_near(32))
$step("城里没有人有这种新伤，布鲁斯观察了一下，认为应该是魔族的手臂，他把鲜血滴进一瓶魔药，魔药由白变黑又变红，这是困魔药水，用它就可以抓住魔","bruce")
$link_this($node_near(32))
$step("")
$link_self($node_near(38),"（没有胳膊）")
$link_self($node_near(39),"（有胳膊）")
$step("不治身亡")
$link_self($node_end(13))
$step("布鲁斯费了很大的力气，把它救活了")
$link_this($node_near(53),$choice_near(52,1))
$step("（白天）中央广场人来人往，你在这里一直晃到晚上，一无所获")
$link_this($node_near(32))
$step("（晚上）你在中央广场的角落里观察，一道黑影掠过")
$link_self($node_near(42),"（有生命晶石）")
$link_self($node_near(43),"（没有）")
$step("翡翠剑从你手中飞出，把黑影钉在了地上，黑影立刻死亡，你只好把尸体拖回去给布鲁斯，布鲁斯很生气")
$link_this($node_end(13),$choice_near(38,1))
$step("你追到城东，黑影把你甩掉了，你无功而返")
$link_this($node_end(13),$choice_near(38,1))
$step("你来到枯井，翡翠剑对黑暗力量有了反应","bruce")
$link_self($node_near(45),"（有提灯）爬下去")
$link_self($node_end(14),"（无提灯）跳下去")
$new_end(14,"END 14 猎魔人")
$link_self($node_near(63),"先回城堡")
$step("你慢慢下到井底，发现了一根鲜血淋漓的胳膊，你没直接碰，用披风裹了起来","bruce")
$link_this($node_near(32))
$step("（白天）你四下问了问，这座屋子已经荒废很久了，以前……")
$link_this($node_near(32))
$step("（晚上）","bruce")
$link_self($node_near(48),"（有困魔药水和生命晶石）","bruce")
$link_self($node_near(49),"（有生命晶石）")
$link_self($node_near(50),"（没有药水）")
$link_self($node_near(64),"（有药水，没有晶石）")
$step("你把药水洒在屋子角落里，轻而易举地抓住了卧底","bruce")
$link_self($node_near(52),"带回去给布鲁斯")
$step("你与魔族缠斗一番，虽然赢了，但它也只剩下了半口气")
$link_self($node_near(37),"带回去")
$step("你没能抓到卧底")
$link_this($node_end(13),$choice_near(38,1))
$step("搬得动你就拿","bruce")
$link_this($node_near(32))
$step("布鲁斯感谢了你","bruce")
$link_self($node_near(53),"接下来怎么办？")
$step("布鲁斯让你养精蓄锐，好好练剑，他会在决战时间定下来后通知你。你专心练剑，布鲁斯花了很多时间来当你的陪练。一个月后，他告诉你三天之后就是决战的日子了。","bruce")
$link_self($node_near(54),"（通过卡萝的考验）")
$link_self($node_near(55),"当天晚上","bruce")
$step("她给你送来了一匹飞马")
$link_this($node_near(55),$choice_near(53,2))
$step("布鲁斯问你需不需要壮行宴会，被你谢绝了，你只想醉一场。你们翻箱倒柜，找出了几瓶满是灰尘的酒水，喝到最后也只是半醉，回房睡觉，到了二楼","bruce")
$link_self($node_near(56),"回房间","bruce")
$link_self($node_near(57),"上三楼（带回了健康的魔族）")
$link_self($node_near(58),"上三楼（没带回健康的魔族）")
$step("你睡到日上三竿，觉得身上积蓄的疲惫一扫而空","bruce")
$link_this($node(6,1),$choice_near(59,1))
$step("布鲁斯看着你，轻声道，你需要好好休息，你回答：我知道")
$link_this($node_near(56),$choice_near(55,1),"回房睡觉")
$link_this($node_near(58),$choice_near(55,3),"跟着他走")
$step("你跟着布鲁斯回了卧室，共度了甜蜜而炙热的一夜，醒来时，布鲁斯已经不在枕边了")
$link_self($node_near(59),"东塔楼")
$link_self($node_near(59),"西塔楼")
$link_self($node_near(59),"城堡一楼")
$link_self($node_near(60),"（之前见过龙蛋）地下室")
$link_self($node_near(61),"（没见过龙蛋）地下室")
$step("你没找到布鲁斯")
$link_self($node(6,1),"备战，两天后")
$step("你走到龙蛋边，忍不住想伸手摸一摸")
$link_self($node_near(62),"摸一下")
$step("你来到地下室，布鲁斯向你介绍了巨龙")
$link_this($node_near(62),$choice_near(60,1),"摸一下")
$step("你把手放到布鲁斯手上，他立刻扭过头，可能是想呵斥你两句，但一道蓝色波纹撞上他的手心，他最终什么都没有说。你说道，你说很快就能孵出来；布鲁斯点点头，是的，于是你笑了笑，这么说来，我可以先见到你再回OA。然后你看向布鲁斯：在哥谭的太阳下。")
$link_this($node(6,1),$choice_near(59,1))
$step("")
$link_this($node_near(33))
$step("你把药水涂在身上，偷袭了魔族，不慎重伤了它")
$link_this($node_near(37),$choice_near(49,1))
$step("决战日","None",6)
$link_self($node_near(2))
$step("布鲁斯")
$link_self($node_near(3))
$step("哥谭百姓")
$link_self($node_near(4))
$step("光明骑士团")
$link_self($node_near(5))
$step("魔王\n战斗关卡")
$link_self($node_end(16),"战斗胜利（睡了布鲁斯）")
$new_end(16,"END16 旭日东升")
$link_self($node_end(17),"战斗胜利（布鲁斯好感度=20）")
$new_end(17,"END17 无尽冒险")
$link_self($node_end(18),"战斗胜利")
$new_end(18,"END18 翡翠长明")
$link_self($node_end(15),"战斗失败")
$new_end(15,"END15 万灵恸哭")
@enduml