@startuml Ch1

!include head.puml

$step("游戏开始","None",1)
$link_self($node_near(2),"继续前进","bruce")
$link_self($node_near(3),"转头回去")
$link_self($node_near(4),"原地睡一觉","sinestro")
$step("见到树上奇怪的影子，翡翠剑上的孔洞发烫，警惕着前方的风险")
$link_self($node_near(5),"追上去","bruce")
$link_this($node_near(3),$choice_near(1,2),"转头回去")
$step("渐渐找回了路，在夜晚的大树上见到了脚印")
$link_self($node_near(6),"原地蹲守")
$link_self($node_near(7),"不关我事")
$link_self($node_near(8),"爬上去")
$step("醒来身边有一团篝火，还有一个人，嘲讽你在野外睡觉都不点火","sinestro")
$link_self($node_near(9),"呛回去")
$link_self($node_near(10),"谢谢你","sinestro")
$link_self($node_near(11),"你哪位")
$step("你追着古怪的阴影一路前进，一直到一处深邃的阴影，一片叶子恰好落在翡翠剑的孔洞上，瞬间燃起了火","bruce")
$link_self($node_near(12),"直接进去")
$link_self($node_near(13),"四处看看（知识+）","bruce")
$step("你在隐蔽处等到天亮，终于听见声响，一个身影从岩缝里钻出来，青苔在他挥手间盖住了脚印，你也在这个时候看清了他的脸，是奥利。你回了小镇。")
$link_self($node_near(52),"去找奥利")
$link_self($node_near(18),"去找卡萝")
$step("你回了小镇，深夜街上空无一人，但有座房子依然亮着灯，是巴里家")
$link_self($node_near(14),"去敲门（知识+2）")
$link_self($node_near(17),"回家睡觉")
$step("摔晕了，醒来已经回到了小镇，巴里说是奥利把你送回来的")
$link_self($node_near(16),"找人带路去龙骨雪山")
$link_this($node_near(52),$choice_near(6,1),"去见他")
1_8-->1_16:1-8-2\n找人带路去龙骨雪山
$step("驯化度-")
$link_this($node_near(11),$choice_near(4,3),"你哪位")
$step("好感度+","sinestro")
$link_this($node_near(11),$choice_near(4,3),"你哪位","sinestro")
$step("他自称瑟尔。他问你是干嘛的，你告诉他你是讨伐魔王的勇者，他问你为什么要讨伐魔王","sinestro")
$link_self($node_near(55),"为了出名")
$link_self($node_near(56),"他是全大陆的威胁")
$link_self($node_near(57),"我想做点什么","sinestro")
$step("从黑洞里进去，是一个隧道，石壁上长的晶石发着冷白的光，你一路前进，晶石颜色愈发五花八门起来，有一些已经落到了地上，你准备捡一块","bruce")
$link_self($node_near(20),"捡块红的")
$link_self($node_near(21),"捡块蓝的")
$link_self($node_near(22),"捡块紫的")
$link_self($node_near(23),"捡块绿的","bruce")
$step("你绕着黑洞走了走，在一棵树上发现了一个刀刻般的痕迹，痕迹很新，好像才刻下没多久。","bruce")
$link_this($node_near(12),"","","bruce")
$step("巴里用鹅毛笔在羊皮纸上画着些什么，见到你很惊讶，问你怎么回来了")
$link_self($node_near(47),"路上迷路了")
$link_self($node_near(48),"想你了啊（好感度+）")
$link_self($node_near(49),"后悔了")
$step("我再给你一次机会")
$link_this($node_near(19),$choice_near(17,2))
$step("附近有几个小镇，去哪里问路")
$link_self($node(2,1),"河流上游的银鳞村")
$link_self($node(2,2),"沿大路走，树林里的百羽镇")
$step("你还要继续冒险吗")
$link_self($node_end(1),"不了，再见")
$new_end(1,"END 01 无事发生")
$link_self($node_near(19),"当然要啊")
$step("你问卡萝还记不记得那棵大树，有没有看到过什么奇怪的东西，卡萝是炼金术师，她说，捡到了一支箭（知识+3）")
$link_this($node_near(52),$choice_near(6,1),"去找奥利")
$step("那你接下来要做什么")
$link_this($node_near(16),$choice_near(8,1))
$link_this($node_near(15),$choice_near(19,1))
$step("火属性晶石")
$link_this($node_near(24),$choice_near(12,0),"继续前进")
$step("水属性晶石")
$link_this($node_near(24),$choice_near(12,0),"继续前进")
$step("空间属性晶石")
$link_this($node_near(24),$choice_near(12,0),"继续前进")
$step("生命属性晶石","bruce")
$link_this($node_near(24),$choice_near(12,0),"继续前进","bruce")
$step("继续前进，周围的晶石越来越多，你眼前一亮，走进了一间屋子，似乎是一间魔法师的书房。书房另一端，有一扇门","bruce")
$link_self($node_near(25),"书架","bruce")
$link_self($node_near(26),"挂毯")
$link_self($node_near(27),"卷轴")
$link_self($node_near(28),"墙上")
$link_self($node_near(29),"直接出门（智力-2）")
$step("光明符文","bruce")
$link_this($node_near(29),$choice_near(24,0),"","bruce")
$step("黑暗符文")
$link_this($node_near(29),$choice_near(24,0))
$step("大地符文")
$link_this($node_near(29),$choice_near(24,0))
$step("雷霆符文")
$link_this($node_near(29),$choice_near(24,0))
$step("你走出去，一步踏出，却看不到路。周围是一片无边无际的星空，转身，门却已经不见了。你只能往前走。隐约似乎看到了一个黑影","bruce")
$link_self($node_near(30),"追上去")
$link_self($node_near(34),"光明符文","bruce")
$step("追了两步就找不到了")
$link_this($node_near(39))
$step("你四处乱走，突然听到一声脆响，星空碎裂，你发现自己站在湖边。一个黑影划过你的眼角，转瞬消失在了森林里。")
$link_self($node_near(32),"追")
$link_self($node_near(33),"不追")
$step("追不上，你又累又饿，回了湖边")
$link_this($node_near(33),$choice_near(31,2))
$step("你在湖边略作休整，沿着水路出去，发现自己到了银鳞村。")
$link_this($node(2,1),$choice_near(16,1))
$step("是一个披着漆黑斗篷的人，他朝你走过来","bruce")
$link_self($node_near(35),"这是哪里")
$link_self($node_near(36),"你是谁")
$step("黑暗法师塔遗迹")
$link_this($node_near(37),$choice_near(34,0),"这是什么地方")
$link_this($node_near(36))
$step("和你一样的人")
$link_this($node_near(37),$choice_near(34,0),"这是什么地方")
$link_this($node_near(35))
$step("这里是一个法阵，已经被黑暗力量浸染，要出去，需要毁掉阵眼。","bruce")
$link_self($node_near(38),"你能做到？")
$link_self($node_near(39),"我能怎么帮你？（好感+1）","bruce")
$step("他再没搭理过你（好感-5）")
$link_self($node_near(31))
$step("找不对劲的地方","bruce")
$link_self($node_near(40),"（知识>=1）脚下踢到了一个黑漆漆的球形","bruce")
$link_self($node_near(31),"知识不足")
$step("你观察了这个球","bruce")
$link_self($node_near(41),"有生命晶石","bruce")
$link_self($node_near(45),"没有生命晶石，见到布鲁斯")
$link_self($node_near(31),"没有生命晶石也没见到布鲁斯")
$step("你刚想叫他过来，口袋里的晶石却发出了耀眼的绿光，自行飞出，落进了原本大小不合适的翡翠剑的孔洞。你挥动翡翠剑，打碎了晶石。星空随之碎裂。","bruce")
$link_self($node_near(44),"（好感+4）没见到布鲁斯")
$link_self($node_near(46),"（好感+10）","bruce")
$step("他给你介绍了法师塔废墟与黑暗力量的关系。（知识+5）","bruce")
$link_this($node_near(43),$choice_near(41,2),"问他的名字","bruce")
$step("他叫布鲁斯，是哥谭人，但你不知道哥谭在哪儿，场面一度十分尴尬。他说，要想多知道翡翠剑的事，可以去天使城。你告别了他，踏上去天使城的路。","bruce")
$link_this($node(2,3),$choice_near(16,3),"海边的天使城","bruce")
$step("你发现自己身处湖边，一个黑影划过眼角")
$link_this($node_near(31))
$step("你叫他过来，他让你走远些，用飞镖打碎的晶石，星空随之碎裂。他向你告别，你才想起还不知道他的名字，你大喊自己的名字，不知道他听没听见。（好感+2）")
$link_this($node_near(33),$choice_near(31,2),"不追")
$step("见到布鲁斯","bruce")
$link_this($node_near(42),$choice_near(41,1),"先问问他法师塔的事","bruce")
$link_this($node_near(43),$choice_near(41,2),"问他的名字")
$step("长老团给的地图不准，你找不到方向，担心越错越远，就回来了，巴里提议去银鳞村找人问路")
$link_this($node(2,1),$choice_near(16,1))
$step("他笑着说你别闹了，说正经的呢")
$link_this($node_near(47),$choice_near(14,1))
$step("巴里有些担心，问你为什么")
$link_self($node_end(1),"怕自己不够强")
$link_self($node_near(50),"（孔洞发烫）知道的太少，准备去找长老团")
$link_self($node_near(51),"（孔洞发烫）知道的太少，有个猜想要去百羽镇查证（知识+1）")
$step("去找长老团询问翡翠剑的秘密，长老团让你去天使城（知识+3）")
$link_this($node(2,3),$choice_near(49,1))
$step("去百羽镇")
$link_this($node(2,2),$choice_near(16,2))
$step("奥利不在家，他家里有做了一半的箭支")
$link_self($node_near(53),"（看到卡萝的箭）")
$link_self($node_near(54),"在屋里等他回来")
$step("仔细看，虽然和那支材料不同，但一些细节上的处理却非常相似（知识+1）")
$link_this($node_near(54),$choice_near(52,2))
$step("四处看看，发现一些端倪，等奥利回来，聊了聊，他带你去百羽镇")
$link_this($node(2,2),$choice_near(16,2))
$step("（好感度-）我希望自己死后几十几百年，依然有人记得我的名字")
$link_this($node_near(58),$choice_near(11,4))
$step("生在其中，无处可躲，为什么不直面未来？")
$link_this($node_near(58),$choice_near(11,4))
$step("（驯化度+）一辈子只有这么长，不如拿来做点别人做不了的事","sinestro")
$link_this($node_near(58),$choice_near(11,4),"sinestro")
$step("柴火突然炸了，把瑟尔吓了一跳","sinestro")
$link_self($node_near(59),"（驯化度>=0）你就这么在野外点火的？","sinestro")
$link_self($node_near(60),"这点胆子，还敢在树林里过夜？")
$link_self($node_near(61),"（好感度>=0）\n有点可爱")
$step("（驯化度++）他没呛声","sinestro")
$link_this($node_near(62),$choice_near(58,4),"sinestro")
$step("（驯化度-）与你何干")
$link_this($node_near(62),$choice_near(58,4))
$step("（好感度-）他问你是不是疯了")
$link_this($node_near(62),$choice_near(58,4))
$step("你把柴火重新收拾了一下，到了后半夜，突然感到不大对劲，瑟尔眼睛泛着金光，和你打了一架，好不容易把他制服","sinestro")
$link_self($node_near(63),"（好感度>0或驯化度>0）","sinestro")
$link_self($node_near(64),"（都<0）把他制住")
$step("瑟尔醒来，问你要不要上他","sinestro")
$link_self($node_near(72),"答应","sinestro")
$link_self($node_end(3),"拒绝")
$new_end(3,"END 03 宁死不屈")
$step("失败，他一下子挣脱了你的控制，不知是不是你的错觉，那一瞬间他的身体似乎变成了烟雾。天亮后你继续前进，发现自己到了百羽镇附近，反倒还沿着你原定规划的路线前进")
$link_self($node_near(65),"进去补给一下")
$link_self($node_near(66),"继续前进")
$step("你听说百羽镇昨晚有人失踪了")
$link_this($node_near(66),$choice_near(64,2),"继续前进")
$step("你又遇到了瑟尔")
$link_self($node_near(67),"（去了百羽镇）")
$link_self($node_near(68),"邀请他一起上路")
$step("你问失踪的人，和你有关吗？他痛快承认")
$link_self($node_near(69),"人在哪儿")
$link_self($node_near(70),"你为什么要抓人")
$step("你们一起走了一段，路边窜出一只兔子撞到他腿上，被黑暗力量缠绕，活活窒息而死")
$link_this($node_near(71),$choice_near(67,3))
$step("回家了，也死了")
$link_this($node_near(71),$choice_near(67,3))
$step("饿了")
$link_this($node_near(71),$choice_near(67,3))
$step("你到底什么来头，他说，你也猜到了吧，我是你要杀的魔王啊")
$link_self($node_end(2),"和他战斗")
$new_end(2,"END 02 出师未捷")
$step("第一步")
$link_self($node_near(73),"先亲")
$link_self($node_near(73),"先摸（评分+2）","sinestro")
$step("第二步")
$link_self($node_near(74),"按地上（评分+3）","sinestro")
$link_self($node_near(74),"按墙上")
$step("第三步")
$link_self($node_near(75),"里面（评分+5）","sinestro")
$link_self($node_near(75),"外面")
$step("做完了")
$link_self($node_near(76),"（10分）好评（好感++）","sinestro")
$link_self($node_near(77),"（5-9分）中评")
$link_self($node_end(4),"（0-4分）差评")
$new_end(4,"END 04 牡丹花下")
$step("他说下次再见，你肩上的牙印突然有点烫","sinestro")
$link_self($node_near(78),"还有下次？")
$link_self($node_near(79),"下次是什么时候")
$link_self($node_near(80),"我怎么联系你","sinestro")
$step("做完他就把你踹一边了，天亮后你到了百羽镇")
$link_this($node(2,2),$choice_near(16,2))
$step("（驯服-）对")
$link_this($node_near(81),$choice_near(76,4))
$step("到时候你就知道了")
$link_this($node_near(81),$choice_near(76,4))
$step("（驯服+，好感+）你不能","sinestro")
$link_this($node_near(81),$choice_near(76,4))
$step("你顺口问了一句，瑟尔给你指了翻越龙骨雪山的路，你决定跟着走","sinestro")
$link_self($node(3,1))

@enduml