@startuml Ch4

!include head.puml!0

$step("你在雪山上绕了挺久，终于找到路下山。（hp+80）","None",4)
$link_self($node_near(3),"下山")
$step("你沿着地图前进，没花多少时间（hp+100）")
$link_this($node_near(3),$choice_near(1,1),"下山")
$step("你接近山脚才发现，与黑暗领域相连的龙骨雪山大部分是冰雪覆盖的悬崖绝壁，两边连通的路屈指可数。你在这条路边遇到了一个酒馆，走进去发现几乎坐满了，只有几桌可以加人")
$link_self($node_near(4),"衣着肮脏的强壮武士")
$link_self($node_near(5),"职业均衡的守卫小队")
$link_self($node_near(6),"带着兜帽的孤身法师")
$step("邀请你同行")
$link_self($node_end(6),"答应")
$new_end(6,"END06 自不量力")
$link_self($node_near(7),"拒绝")
$step("了解了很多知识（知识+5）")
$link_self($node_near(7),"出发")
$step("你在他对面坐下，要了一点热食，突然发现对面的人非常熟悉，你叫出他的名字，立刻引来了攻击，你们花了好大力气逃掉，躲在巴里的藏身处。他把你抱怨一顿，你反问他那么强的魔法是哪儿来的")
$link_self($node_near(8),"你到底是什么人")
$link_self($node_near(9),"你在小镇干什么")
$link_self($node_near(10),"你怎么会在这儿")
$step("孤身上路\n战斗关卡")
$link_self($node_end(7),"胜利（赛叔好感度<5）")
$new_end(7,"END07 无心之过")
$link_self($node_near(13),"胜利（赛叔好感度>=5）","sinestro")
$link_self($node_end(6),"失败")
$step("雷电系大魔法师，光明骑士团的一员，如果你需要的话，还是你的队友")
$link_this($node_near(6))
$link_this($node_near(11),$choice_near(6,4),"我可以相信你吗")
$step("观察长老团，他们有些不愿意让人知道的秘密，他怀疑和天使城的谜团有关")
$link_this($node_near(6))
$link_this($node_near(11),$choice_near(6,4),"我可以相信你吗")
$step("说来话长，但现在你们的目标是一致的，都要深入黑暗领域")
$link_this($node_near(6))
$link_this($node_near(11),$choice_near(6,4),"我可以相信你吗")
$step("巴里表情一僵，你哈哈大笑，他才意识到你在耍他。你们休息一夜就上路了。从龙骨雪山出去先是战区，战区非常混乱，常常会遇到魔的袭击，守卫小队会定期进来巡逻，防止战区的魔太多，侵扰龙骨雪山")
$link_self($node_near(12),"胜利")
$link_self($node_end(6),"失败")
$step("你们在战区一路走一路杀，抵达了黑暗领域真正的边境，你们被巡视的魔发现了，陷入苦战，情急之下，巴里使用了一个传送魔法，你们到了哥谭一座瞭望塔顶上")
$link_self($node(5,4))
$step("你穿过战区，潜入黑暗领域，紧张地躲避着魔的巡逻，你肩头的牙印忽然发烫，瑟尔出现在你面前：“还记得我吗？哈尔？”","sinestro")
$link_self($node_near(14),"你哪位")
$link_self($node_near(15),"有什么事")
$link_self($node_near(16),"你又要我上你吗","sinestro")
$step("（好感度-）")
$link_self($node_near(17),"这里不安全")
$link_self($node_near(18),"脱衣服","sinestro")
$link_self($node_near(19),"你真奇怪")
$step("")
$link_this($node_near(14))
$step("（驯化度+）","sinestro")
$link_this($node_near(14))
$step("（驯化度-）")
$link_this($node_near(20),$choice_near(14,4))
$step("（好感度+）","sinestro")
$link_this($node_near(20),$choice_near(14,4))
$step("")
$link_this($node_near(20),$choice_near(14,4))
$step("你又和瑟尔搞了一次，这次留意到了更多的细节，你忍不住开始思索他究竟是什么人，可瑟尔的话声打断了你的思绪：“你还是要去杀了魔王吗”","sinestro")
$link_self($node_near(29),"没错","sinestro")
$link_self($node_near(22),"我在考虑")
$step("瑟尔表示他也要去魔王宫殿，你们可以同路","sinestro")
$link_self($node_near(23),"答应","sinestro")
$link_self($node_near(24),"拒绝")
$step("黑暗生物有着自己的意识，就意味着可以交流，或许双方可以共存（驯化度归零）")
$link_self($node_near(21))
$step("你们一同前往魔王宫殿","sinestro")
$link_self($node_near(25),"（同路）","sinestro")
$step("（好感度归零）瑟尔祝你好运")
$link_this($node_near(26),$choice_near(23,2),"（独自）")
$step("你发现瑟尔身上有许多疑点，比起人，更像是个魔，信上的预言萦绕在你心头，你总觉得背后有着一个会令你大吃一惊的秘密。最后，你们到了魔王的宫殿外，宏伟的建筑近在咫尺，瑟尔停下了脚步","sinestro")
$link_self($node_near(27),"（驯化度=8）打起来之前，不请我进你家看看吗？","sinestro")
$link_self($node_near(28),"（好感<8）拔剑")
$link_self($node_end(10),"怎么了？")
$new_end(10,"END10 翡翠暮光")
$step("你独自抵达了魔王的宫殿，瑟尔就站在那里等你")
$link_this($node_near(25))
$step("瑟尔拒绝，你们打了起来，最终你获胜，笑着问他现在可你带你参观了吗","sinestro")
$link_self($node_end(11),"（好感度=8）再给他一次机会","sinestro")
$new_end(11,"END11 家养猫咪")
$link_self($node_end(12))
$new_end(12,"END12 晴空万里")
$step("你战败了")
$link_self($node_end(8),"（驯化度满）")
$new_end(8,"END08 不见天日")
$link_self($node_end(9),"（驯化度<8）")
$new_end(9,"END09 命丧他乡")
$step("我的想法还没变","sinestro")
$link_this($node_near(21),$choice_near(22,1),"sinestro")

@enduml